### ISSUE TITLE
Datenpunkte liefern keine Werte

### ISSUE THREAD

**Issue by dani1993K** [Pittini/iobroker-nodemihome#10]
Hi, 
ich benutze die beiden Air Purifier 3H und 3C.
Zu beiden Geräten werden auch die Datenpunkte erstellt, jedoch wird hier nichts aktuallisiert und ich kann auch nichts setzen.

Weiter unten führe ich mal das Log aus dem Iobroker auf. Was mir komisch vor kommt, ist dass zunächst angezeigt wird, dass der 3C Purifier (zhimi.airpurifier.mb4) erstellt und erkannt wird, und dann auf einmal nicht mehr supported ist. Die Datenpunkte wurden alle erstellt, aber hier gibt es keine Updates. Da ich kein Programmierer bin, hab ich mir jetzt mal zusammengereimt, dass das vermutlich daran liegt dass der Pull Request für das Gerät noch nicht durch ist. Liege ich mit der Annahme richtig?

Der 3H Purifier wird ja super erkannt, aber auch hier wurden lediglich die Datenpunkte erkannt. Updates kommen hier leider auch nicht rein und ich kann auch nichts steuern. 

**javascript.0 | 2021-02-12 13:39:57.722 | error | (4627)     at processTicksAndRejections (internal/process/task_queues.js:93:5)
-- | -- | -- | --
javascript.0 | 2021-02-12 13:39:57.721 | error | (4627)     at runMicrotasks (<anonymous>)
javascript.0 | 2021-02-12 13:39:57.721 | error | (4627)     at main (script.js.Air_Purifier.AllMyMi-V0.2.8.js:547:11)
javascript.0 | 2021-02-12 13:39:57.721 | error | (4627)     at CreateDevices (script.js.Air_Purifier.AllMyMi-V0.2.8.js:615:36)
javascript.0 | 2021-02-12 13:39:57.720 | error | (4627)     at Object.createDevice [as device]  (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/device.js:8:11)
javascript.0 | 2021-02-12 13:39:57.720 | error | (4627) script.js.Air_Purifier.AllMyMi-V0.2.8.js: Error: Model zhimi.airpurifier.mb4 is not supported
javascript.0 | 2021-02-12 13:39:57.718 | info | (4627) script.js.Air_Purifier.AllMyMi-V0.2.8.js: Now creating device  for zhimi.airpurifier.mb4 / did / ip /  token / 10000**
javascript.0 | 2021-02-12 13:39:57.717 | info | (4627) script.js.Air_Purifier.AllMyMi-V0.2.8.js: Reaching CreateDevices
javascript.0 | 2021-02-12 13:39:57.715 | info | (4627) script.js.Air_Purifier.AllMyMi-V0.2.8.js: Reaching WriteGenericDpValues()
javascript.0 | 2021-02-12 13:39:57.714 | info | (4627) script.js.Air_Purifier.AllMyMi-V0.2.8.js: Reaching main
javascript.0 | 2021-02-12 13:39:57.713 | info | (4627) script.js.Air_Purifier.AllMyMi-V0.2.8.js: 49 States created, now setting up channels!
javascript.0 | 2021-02-12 13:39:57.647 | info | (4627) script.js.Air_Purifier.AllMyMi-V0.2.8.js: Reaching CreateStates()
javascript.0 | 2021-02-12 13:39:57.646 | info | (4627) script.js.Air_Purifier.AllMyMi-V0.2.8.js: Reaching PrepareDeviceDps, did=did model=zhimi.airpurifier.mb3
javascript.0 | 2021-02-12 13:39:57.646 | info | (4627) script.js.Air_Purifier.AllMyMi-V0.2.8.js: Device Luftreiniger Schlafzimmer is supported, creating DataPoints
**javascript.0 | 2021-02-12 13:39:57.646 | info | (4627) script.js.Air_Purifier.AllMyMi-V0.2.8.js: Reaching PrepareDeviceDps, did=did model=zhimi.airpurifier.mb4
javascript.0 | 2021-02-12 13:39:57.645 | info | (4627) script.js.Air_Purifier.AllMyMi-V0.2.8.js: Device Luftreiniger Wohnzimmer is supported, creating DataPoints**
javascript.0 | 2021-02-12 13:39:57.645 | info | (4627) script.js.Air_Purifier.AllMyMi-V0.2.8.js: Now searching for supported Devices...
javascript.0 | 2021-02-12 13:39:57.645 | info | (4627) script.js.Air_Purifier.AllMyMi-V0.2.8.js: Roborock
javascript.0 | 2021-02-12 13:39:57.644 | info | (4627) script.js.Air_Purifier.AllMyMi-V0.2.8.js: Luftreiniger Schlafzimmer
javascript.0 | 2021-02-12 13:39:57.644 | info | (4627) script.js.Air_Purifier.AllMyMi-V0.2.8.js: Luftreiniger Wohnzimmer
javascript.0 | 2021-02-12 13:39:57.643 | info | (4627) script.js.Air_Purifier.AllMyMi-V0.2.8.js: Found 3 MiHome Devices, those are:
javascript.0 | 2021-02-12 13:39:57.450 | info | (4627) script.js.Air_Purifier.AllMyMi-V0.2.8.js: Retrieving your in de registered MiHome Devices
javascript.0 | 2021-02-12 13:39:57.450 | info | (4627) script.js.Air_Purifier.AllMyMi-V0.2.8.js: You are already logged in, login canceled
javascript.0 | 2021-02-12 13:39:57.449 | info | (4627) script.js.Air_Purifier.AllMyMi-V0.2.8.js: registered 0 subscriptions and 0 schedules
javascript.0 | 2021-02-12 13:39:57.446 | info | (4627) script.js.Air_Purifier.AllMyMi-V0.2.8.js: Reaching init
javascript.0 | 2021-02-12 13:39:57.446 | info | (4627) script.js.Air_Purifier.AllMyMi-V0.2.8.js: Starting AllMyMi V.0.2.8
javascript.0 | 2021-02-12 13:39:57.424 | info | (4627) Start javascript script.js.Air_Purifier.AllMyMi-V0.2.8.js

**Comment by Pittini** [comment]
> Da ich kein Programmierer bin, hab ich mir jetzt mal zusammengereimt, dass das vermutlich daran liegt dass der Pull Request für das Gerät noch nicht durch ist. Liege ich mit der Annahme richtig?

So isses. Es fehlen Dir die Definitionsdateien. Und zwar die:
zhimi.airpurifier.mb3.js
zhimi.airpurifier.mb4.js

Bis der PullRequest gemerged ist, kannste Dir die Dateien selber einbinden. Zu finden sind die bei meiner Fork für Node-mihome, also hier: _https://github.com/Pittini/node-mihome/tree/master/lib/devices_

und die müssen in dieses Verzeichnis: _/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/devices/_

Dann den JS Controller neustarten und es sollte laufen.

**Comment by dani1993K** [comment]
Klappt super
und vielen Dank für deine schnelle Antwort ;-)

Die Datei zhimi.airpurifier.mb3.js war bereits in dem Verzeichnis angelegt. Ich hab die nur mal kurz überlfogen und die unterscheidet sich etwas von der, die du mir verlinkt hast. Ich hab die einfach mit der neuen überschrieben und die alte erst gar nicht getestet.

Also nochmal danke und weiterhin viel Spaß beim coden :-)
