### ISSUE TITLE
Xiaomi Mi Air Purifier 3H: You are assigning a boolean to the state "alarm.alarm"

### ISSUE THREAD

**Issue by mesche** [Pittini/iobroker-nodemihome#14]
Bei meinem Purifier 3H bekomme ich folgende Meldung.

`You are assigning a boolean to the state "javascript.0.MiHome.****.alarm.alarm" which expects a number. Please fix your code to use a number or change the state type to boolean.`

Grund: Der Datenpunkt "alarm.alarm" wurde als Number angelegt, aber als Wert wurde ein Boolean gespeichert.

Script-Version: 0.2.8

**Comment by Pittini** [comment]
Fixed with 0.2.9
