### ISSUE TITLE
Cannot install npm packet: Pittini/node-mihome

### ISSUE THREAD

**Issue by nicedevil007** [Pittini/iobroker-nodemihome#15]
Heya,

I'm not able to install your awesome script right now. I did everything from your manual to get it to work.
I also tryed to change the repository to Pittini/iobroker-nodemihome but that didn't work as well.

Here is a Screenshot from my ioBroker:
![image](https://user-images.githubusercontent.com/17103076/110856249-b27b8e80-82b7-11eb-85d1-0999a840aaea.png)

**Comment by stony2k** [comment]
Did you edit the script like me? I just found the error, because I also edit the script from
const mihome = require('node-mihome');
to
const mihome = require('Pittini/node-mihome');

I changed it back to require('node-mihome'); and the script started to read my devices (but I can't control them). @Pittini do I have to open a separate issue for that?

**Comment by nicedevil007** [comment]
I created mine like this:

![image](https://user-images.githubusercontent.com/17103076/110859432-b4475100-82bb-11eb-8305-861aa6f50021.png)

And after saving I get this:
![image](https://user-images.githubusercontent.com/17103076/110859524-d7720080-82bb-11eb-9cc9-32fcabfa9783.png)

**Comment by stony2k** [comment]
Did you read my message carefully? You made the exact error I described above :)

**Comment by nicedevil007** [comment]
Sry didn't mention that I had it the way you described it should be before posting the screen. I was just testing and testing, and it didnt work :( Tested both. Right now I have it again with ```const mihome = require('node-mihome');````and it is still not starting.

EDIT: Ok restarted my container for ioBroker now and it is workiiiiiiiiiiiiiiiiiiing :D

**Comment by stony2k** [comment]
Nice. Do you have a Mi Air Purifier 3H? If yes, can you control it? The scripts creates datapoints for mine, but does not fill them with values and I can't control the device.

**Comment by nicedevil007** [comment]
Yeah it is doing so! I'm already building node-red stuff around this to automate it and so on.
I tryed changing values in ioBroker directly and it was working.

**Comment by stony2k** [comment]
Hrm.. so what am I doing wrong? Do you have any script errors?

**Comment by nicedevil007** [comment]
Nope nothing here in script now. I'm using 5.0.14 for the scriptengine.
Maybe something is blocking on your firewall?

**Comment by stony2k** [comment]
But all my devices (including the purifier) are recognized and created. Seems fine so far.

Lets discuss this in the corresponding issue. You should close this issue :)
