### ISSUE TITLE
(8369) Cannot install npm packet: Pittini/node-mihome

### ISSUE THREAD

**Issue by dschuwa** [Pittini/iobroker-nodemihome#17]
Hallo,

ich habe mir mal ein Testsystem (jungfräulich) an die in Betriebnahme des Scripts gesetzt. 
Bei der Installation des Pittini/node-mihome bekam ich jedoch eine Fehlermeldung im Log:

javascript.0 | 2021-03-12 11:03:43.813 | error | (8369) Cannot install npm packet: Pittini/node-mihome
-- | -- | -- | --
javascript.0 | 2021-03-12 11:03:43.722 | info | (8369) found 0 vulnerabilities
javascript.0 | 2021-03-12 11:03:43.719 | info | run `npm fund` for details
javascript.0 | 2021-03-12 11:03:43.719 | info | 4 packages are looking for funding
javascript.0 | 2021-03-12 11:03:43.719 | info | (8369)
javascript.0 | 2021-03-12 11:03:43.632 | info | updated 1 package and audited 51 packages in 20.806s
javascript.0 | 2021-03-12 11:03:43.632 | info | (8369) + node-mihome@0.0.32
javascript.0 | 2021-03-12 11:03:21.545 | info | (8369) npm install Pittini/node-mihome --production (System call)
javascript.0 | 2021-03-12 11:03:21.508 | info | (8369) found 0 vulnerabilities
javascript.0 | 2021-03-12 11:03:21.504 | info | run `npm fund` for details
javascript.0 | 2021-03-12 11:03:21.504 | info | 4 packages are looking for funding
javascript.0 | 2021-03-12 11:03:21.504 | info | (8369)
javascript.0 | 2021-03-12 11:03:21.395 | info | updated 1 package and audited 51 packages in 25.742s
javascript.0 | 2021-03-12 11:03:21.395 | info | (8369) + node-mihome@0.0.32
javascript.0 | 2021-03-12 11:02:40.555 | info | (8369) npm install Pittini/node-mihome --production (System call)
javascript.0 | 2021-03-12 11:02:40.477 | info | (8369) found 0 vulnerabilities
javascript.0 | 2021-03-12 11:02:40.473 | info | run `npm fund` for details
javascript.0 | 2021-03-12 11:02:40.473 | info | 4 packages are looking for funding
javascript.0 | 2021-03-12 11:02:40.473 | info | (8369)
javascript.0 | 2021-03-12 11:02:40.352 | info | updated 1 package and audited 51 packages in 20.607s
javascript.0 | 2021-03-12 11:02:40.352 | info | (8369) + node-mihome@0.0.32
javascript.0 | 2021-03-12 11:02:18.396 | info | (8369) npm install Pittini/node-mihome --production (System call)
javascript.0 | 2021-03-12 11:02:18.297 | info | (8369) found 0 vulnerabilities
javascript.0 | 2021-03-12 11:02:18.294 | info | run `npm fund` for details
javascript.0 | 2021-03-12 11:02:18.294 | info | 8 packages are looking for funding
javascript.0 | 2021-03-12 11:02:18.294 | info | (8369)
javascript.0 | 2021-03-12 11:02:18.197 | info | added 36 packages from 20 contributors and audited 51 packages in 23.174s
javascript.0 | 2021-03-12 11:02:18.197 | info | (8369) + node-mihome@0.0.32
javascript.0 | 2021-03-12 11:01:53.759 | info | (8369) npm install node-mihome --production (System call)
javascript.0 | 2021-03-12 11:01:53.709 | info | (8369) starting. Version 5.0.14 in /opt/iobroker/node_modules/iobroker.javascript, node: v12.21.0, js-controller: 3.2.16
host.raspberrypi | 2021-03-12 11:01:51.080 | info | instance system.adapter.javascript.0 started with pid 8369

Bei node-mihome hat es auf dem Testsystem funktioniert. Jetzt werde ich mal schauen ob ich auch die Daten aus meinen H2 bekomme.

Viele Grüße

**Comment by nicedevil007** [comment]
Schau mal hier vorbei https://github.com/Pittini/iobroker-nodemihome/issues/15

**Comment by stony2k** [comment]
Witzig, aber ich habe das gleiche Problem (gerade in der Log gesichtet). Meine Log sieht in etwa so aus wie bei @dschuwa. Korioserweise kann er legt aber zumindest meine Xiaomi Geräte an. @dschuwa bei dir auch?

Ich habe den Ordner **node-mihome** in **/opt/iobroker/node_modules/iobroker.javascript/node_modules/** gelöscht, den Javascriptadapter neugestartet und er hat den Ordner wieder erstellt. Das bedeutet doch eigentlich, dass der Fork von @Pittini heruntergeladen wurde, oder? Unter zusätzliche NPM-Module habe ich ausschließlich **Pitti/node-mihome** drin stehen.

Im Script selber habe ich den Eintrag in Zeile 3 bei **const mihome = require('node-mihome');** belassen.

**Comment by stony2k** [comment]
@dschuwa läuft denn dein Script? Bei mir läuft es, trotz des Fehlers Cannot install npm packet: Pittini/node-mihome, denn er kopiert sich die Dateien aus dem Fork ins Verzeichnis /opt/iobroker/node_modules/iobroker.javascript/node_modules/

**Comment by dschuwa** [comment]
Richtig, bei mir funktioniert das Script, ich kann auch die Daten von meinem H2 sehen.
Das könnte auch daran liegen das ich beiden node-mihome eingetragen hatte.
Werde mir das in den nächsten Tagen noch mal ansehen, evtl. noch einmal testen.

**Comment by Pittini** [comment]
Leider ist das ganze Systemebene wo ich nich wirklich nen Plan hab, das Skript läuft an sich.
Da es aber den Anschein hat, dass die Probleme immer in Zusammenhang mit der direkten Forkinstallation zusammenhängen, werd ich den Tipp aus der Anleitung wieder rausnehmen und Euch bitten das wieder auf blanko node-mihome zu stellen. 
Ja ich weis, dasses nervt, das der Entwickler nicht reagiert, aber glücklicher Weise wird die node-mihome nur erneuert wenn der JS-Adapter upgedatet wird.
Der Weg wäre also, erst regulär node-mihome anzugeben und dann die für Eure Geräte relevanten Definitionsdateien aus der Fork in Euer node-mihome Verzeichnis zu kopieren. Nach neustart des JS Adapters sollte dann alles laufen.

**Comment by stony2k** [comment]
Oder wir testen wie [hier vorgeschlagen](https://github.com/Pittini/iobroker-nodemihome/issues/16#issuecomment-798870231), ob trotzdem alles aus deinem Form geladen wird. In der Readme dann enstprechend eine Information eintragen: 
"Es kann der Fehler vorkommen, dass in der Log der Fehler _Cannot install npm packet: Pittini/node-mihome_ erscheint, dennoch wird mein Fork erfolgreich heruntergeladen. Dies ist allerdings eine temporäre Lösung, bis der Entwickler meine Pullrequests übernommen hat" 

Und ich würde vorschlagen in der Readme noch zu ergänzen:
"Bitte in Zeile 3 des Scripts _const mihome = require('node-mihome');_ nicht ändern."

Hoffe es verwirrt nicht, dass ich mich hier auf deine andere Repo beziehe :D

**Comment by dschuwa** [comment]
Ich versuche heute Abend den Test Raspi und ioBroker neu zu installieren, ich werde dann mal node-mihome weglassen und nur den  Pittini/node-mihome eintragen. Mal sehen ob es dann auch funktioniert.
Wenn ja, dann würde ich mich dem Vorschlag von @stony2k anschließen.
Also noch ein klein bisschen Geduld, "Alter" Man ist kein D-Zug :-)

**Comment by dschuwa** [comment]
So Test beendet.
Also, jetzt nur NPN-Module Pittini/node-mihome eingetragen.
Adapter leuchtet rot - 2 Minuten gewartet, dann Adapter neu gestartet und ins Log geschaut. Installationsaufrufe und dann kommt die besagte Fehlermeldung.
Diese ignoriert und weiter gemacht, Script kopiert und Zugangsdaten eingetragen - 2 Minuten gewartet.
In den Objekten unter dem Adapter meine 2 Geräte gefunden, der H2 war auch dabei und auch die Daten waren alle vorhanden.
Daher mein Vorschlag: Textvorschlag wie von @stony2k nehmen und alles ist erstmal gut.

**Comment by Pittini** [comment]
Ich mach hier mal zu.
