### ISSUE TITLE
Mi Geräte lassen sich plötzlich nicht mehr steuern

### ISSUE THREAD

**Issue by stony2k** [Pittini/iobroker-nodemihome#19]
Es werden noch immer alle Geräte aus der Mi Cloud erfasst und Datenpunkte erstellt. Habe dazu alle gelöscht und das  Script neu gestartet. Wenn ich z. B. mit dem Yeelight Adapter die Lampe steuere, wird der Datenpunkt vom Script aktualisiert. Beim Mi Air Purifier 3/3H werden die Datenpunkte gar nicht mehr aktualisiert Möchte ich aber den Datenpunk selbst aktualisieren, viele Fehler. Hier mal die Log:

[error.log](https://github.com/Pittini/iobroker-nodemihome/files/6291487/error.log)

**Comment by Pittini** [comment]
Sieht mir aufn ersten Blick so aus als ob die node-mihome upgedatet wurde (passiert z.B. wenn man den JS Adapter aktualisiert) und es somit falsche oder fehlende Definitionsdateien gibt. Ich hab die für solche Fälle hier im Repo liegen, einfach die für Dich relevanten wieder ins node-mihome Verzeichnis kopieren und neustart. Das wird immer wieder passieren, bis der node-mihome Entwickler mal in die Pötte kommt und den Pullrequest merged. Kannst ja mal dort nen Issue machen, vielleicht hilfts.

**Comment by stony2k** [comment]
Jetzt kommt das kuriose: Ich habe den Javascript Adapter neugestartet und es geht wieder. Ohne Dateien kopiert zu haben. Das ist zwar keine technische Lösung, aber es geht wieder. Kannst du dir das erklären?

**Comment by Pittini** [comment]
Nö, mir alles erklären können zu wollen hab ich schon vor Jahrzehnten aufgegeben ;) . Aber neustarts sind ja immer ein probates Mittel und bei Fehler das erste was ich mach.
