### ISSUE TITLE
Xiaomi Mi Fan 2s

### ISSUE THREAD

**Issue by janhp** [Pittini/iobroker-nodemihome#20]
Dear dev,

unforunatly, I can not write the power (on/off) values of my mi fan 2s. any chance you can fix that?

**Comment by Pittini** [comment]
Maybe. Whats the exact modelname? You found it at the "info" datapoint. And....are you shure this device is supportet in the script?

**Comment by janhp** [comment]
![11111](https://user-images.githubusercontent.com/71586781/114576711-ad757a80-9c7b-11eb-9f32-09f1fc03f51e.png)

**Comment by Pittini** [comment]
Ok, tnx. The Device is supportet, but completely untested. So please, try everything and report. But first lets solve the power problem. Please try to change line 256 from:

`"power": async function (obj, val) { await device[obj].setPower(val ? 'on' : 'off') },`

to

`"power": async function (obj, val) { await device[obj].setPower(val) },`

**Comment by janhp** [comment]
sure I will check that later and let you know

**Comment by Pittini** [comment]
I'm still waiting for "later".

**Comment by janhp** [comment]
worked. thanks :)

**Comment by Pittini** [comment]
Everything is tested and works or just the power button?

**Comment by janhp** [comment]
tested just the power button
