### ISSUE TITLE
Mi LED Desk Lamp 1S power off

### ISSUE THREAD

**Issue by janhp** [Pittini/iobroker-nodemihome#21]
Hi DEV,

es scheint einen Bug im Skript zu geben, meine Mi LED Desk Lamp 1S lässt sich leider nicht ausschalten (power off). Power On hingegen funktioniert.

An was kann das liegen?

Danke dir!

**Comment by Pittini** [comment]
Seltsam, eigentlich sollte beides gehen, oder halt nicht. Aber egal, die Lösung könnte die gleiche sein wie ich Dir beim Fan schon sagte, nur isses diesmal die Zeile 375:

`"power": async function (obj, val) { await device[obj].setPower(val ? 'on' : 'off') },`

da machste wieder hinten das "? 'on' : 'off'" ' weg, also dann so:

`"power": async function (obj, val) { await device[obj].setPower(val) },`

**Comment by janhp** [comment]
wunderbar hat geklappt danke.
