### ISSUE TITLE
Xiaomi AirPurifier 3C "not supported" ; zhimi.airpurifier.mb4

### ISSUE THREAD

**Issue by Solilord** [Pittini/iobroker-nodemihome#22]
Hey, beim starten vom Skript bekomme ich angehängtes log.

Der mb4 (3C) soll ja aber eigentlich unterstützt werden.
Zugangsdaten sind richtig eingetragen und der 3C ist auf in meiner MiHome App. Land ist Deutschland (und das stimmt auch alles)

Der Ordnerbaum für den purifier wird auch angelegt, aber alle werte (bis auf die bei info) sind "null"

javascript.0 | 2021-04-20 14:44:23.841 | error | (21601)     at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- | -- | -- | --
javascript.0 | 2021-04-20 14:44:23.840 | error | (21601)     at runMicrotasks (<anonymous>)
javascript.0 | 2021-04-20 14:44:23.840 | error | (21601)     at main (script.js.smarthome.sontiges.Luftreiniger:564:11)
javascript.0 | 2021-04-20 14:44:23.840 | error | (21601)     at CreateDevices (script.js.smarthome.sontiges.Luftreiniger:632:36)
javascript.0 | 2021-04-20 14:44:23.839 | error | (21601)      at Object.createDevice [as device]  (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/device.js:8:11)
javascript.0 | 2021-04-20 14:44:23.838 | error | (21601) script.js.smarthome.sontiges.Luftreiniger: Error: Model zhimi.airpurifier.mb4 is not supported
javascript.0 | 2021-04-20 14:44:23.835 | info | (21601)  script.js.smarthome.sontiges.Luftreiniger: Now creating device for  zhimi.airpurifier.mb4 / 362412154 / XXX.XXX.XXX.XXX /  XXXXXXXXXXXXXXXXXXXXXXXXXXXX / 10000 ((<- Hab den token und die IP entfernt))
javascript.0 | 2021-04-20 14:44:23.412 | info | (21601) script.js.smarthome.sontiges.Luftreiniger: Device Mi Control Hub is supported, creating DataPoints
javascript.0 | 2021-04-20 14:44:23.411 | info | (21601) script.js.smarthome.sontiges.Luftreiniger: Device Mi Air Purifier 3C is supported, creating DataPoints
javascript.0 | 2021-04-20 14:44:23.411 | info | (21601) script.js.smarthome.sontiges.Luftreiniger: Now searching for supported Devices...
javascript.0 | 2021-04-20 14:44:23.411 | info | (21601) script.js.smarthome.sontiges.Luftreiniger: Staubsauger
javascript.0 | 2021-04-20 14:44:23.410 | info | (21601) script.js.smarthome.sontiges.Luftreiniger: Mi Control Hub
javascript.0 | 2021-04-20 14:44:23.410 | info | (21601) script.js.smarthome.sontiges.Luftreiniger: Mi Air Purifier 3C
javascript.0 | 2021-04-20 14:44:23.409 | info | (21601) script.js.smarthome.sontiges.Luftreiniger: Found 3 MiHome Devices, those are:
javascript.0 | 2021-04-20 14:44:23.092 | info | (21601) script.js.smarthome.sontiges.Luftreiniger: Retrieving your in de registered MiHome Devices

Danke! 
Florian

**Comment by Pittini** [comment]
Vermutlich fehlt die Def Datei. Schau mal ob Du unter:
`/opt/iobroker/node_modules/iob`roker.javascript/node_modules/node-mihome/lib/device

eine Datei namens zhimi.airpurifier.mb4.js hast. Wenn nein oder anderer Inhalt dann von hier https://github.com/Pittini/iobroker-nodemihome/tree/main/DefinitionfilesForNode-Mihome holen und reinkopieren. JS Adapter neustarten und guggen obs dann läuft.

**Comment by Solilord** [comment]
Danke für deine Antwort!

Ich hab leider keine Benachrichtigung bekommen, dass du geschrieben hast.

Das war in der Tat der Fehler. Jetzt gehts wunderbar! Dankeschön!
