### ISSUE TITLE
Xiaomi Air Purifier 2H - zhimi.airpurifier.mc2 Datenpunkte leer.

### ISSUE THREAD

**Issue by tobasium** [Pittini/iobroker-nodemihome#25]
Es werden Objekte erstellt aber nicht befüllt.

![image](https://user-images.githubusercontent.com/23247891/117583220-43c77f80-b106-11eb-906a-cbeee3ab1fda.png)

[log.txt](https://github.com/Pittini/iobroker-nodemihome/files/6448188/log.txt)

Habe mal alles aus dem Log rauskopiert vielleicht hilft es.

**Comment by Pittini** [comment]
Log sieht so aus als wär alles ok, kommen nur keine DAten. Die Frage is jetzt, warum?

**Comment by tobasium** [comment]
Also wen ich was tun kann sag an. Kann sowas am miio Adapter liegen? Der läuft und über den kann ich aktuell auch ansteuern.

**Comment by dontobi** [comment]
Ich würde den miio ausschalten. Ich glaube aber, dass die Datei vom 2H in der node-mihome nicht richtig ist. Bevor ich den Support des 2H erarbeitet habe, hatte ich auch keine Daten erhalten.
Kopier doch bitte Mal den Inhalt der folgenden Datei hier rein.
/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/devices/zhimi.airpurifier.mc2.js

Dazu sei gesagt, dass mein. 2H ohne Probleme mit dem Script läuft.

**Comment by Pittini** [comment]
Jap, da es eine Version in https://github.com/Pittini/iobroker-nodemihome/tree/main/DefinitionfilesForNode-Mihome gibt, is da was anders, also wenn es eine gibt, immer die aus meinem Verzeichnis nehmen.

**Comment by tobasium** [comment]
Hallo Zusammen,

ich habe die Datei ausgetauscht und es geht jetzt. Vielen Dank für die Unterstützung.
