### ISSUE TITLE
NPM ISSUE with other adapters

### ISSUE THREAD

**Issue by janhp** [Pittini/iobroker-nodemihome#26]
HI Pittini, bei dem Versuch neue Adapter zu installieren, erhalte ich leider folgende Fehlermeldung:
`$ ./iobroker add yahka  --host raspberrypi
NPM version: 6.14.12
npm install iobroker.yahka@0.12.0 --loglevel error --prefix "/opt/iobroker" (System call)
npm 
ERR! code EINVALIDTAGNAME
npm 
ERR! Invalid tag name "node-mihome@0.0.32": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2021-05-11T06_57_24_809Z-debug.log
ERROR: host.raspberrypi Cannot install iobroker.yahka@0.12.0: 1
ERROR: process exited with code 25`

**Comment by Pittini** [comment]
Hmm, da kann ich Dir nicht helfen, damit hat mein Skript ja maximal indirekt zu tun. Von Systemebene hab ich keine Ahnung, aber drei Vorschläge für Dich was Du tun kannst.
1. die node-mihome aus dem JS Adpter rausnehmen. Gerät neu starten und dann versuchen Yahka zu installieren, danach die node-mihome wieder eintragen.
2. Thread im Forum aufmachen und Thomas Braun taggen (oder den vorhandenen Thread nutzen: https://forum.iobroker.net/topic/39388/vorlage-xiaomi-airpurifier-3h-u-a-inkl-token-auslesen/151).
3. Issue bei node-mihome aufmachen (wenig Erfolg versprechend da der Dev sich seit Monaten nich mehr meldet)

**Comment by Pittini** [comment]
Konntest das im Forum klären? Wenn ja bitte mach hier zu.

**Comment by janhp** [comment]
Ja hat geklappt danke.
