### ISSUE TITLE
Support for Mi Smart Standing Fan 1C

### ISSUE THREAD

**Issue by klotzma** [Pittini/iobroker-nodemihome#27]
Hello everyone, 
could you add support for the Mi standing fan 1C ?

Thanks

![16207405053273313081928091953253](https://user-images.githubusercontent.com/45261052/117825391-97a1a800-b26f-11eb-81af-8ee0a63ee6f9.jpg)

**Comment by Pittini** [comment]
Maybe. First you have to install and run the script as described and then tell me the exact model from the Infochannel (Its not the same as shown in the pic). Maybe there are Errormsgs ...Device is not supportet, ignore it.
After that i can make a testintegration for you. I don't have this device, so all tests are to made by you.

**Comment by klotzma** [comment]
The Model is dmaker.fan.1c.
Ok thanks.

**Comment by Pittini** [comment]
Ok, give it a try. Copy the dmaker.fan.1c.js [from here](https://github.com/Pittini/iobroker-nodemihome/tree/main/DefinitionfilesForNode-Mihome) to your node-mihome devices directory (see scriptmanual) and restart the js Adapter. Install the new Scriptversion 0.2.15 and start it. Test and Feedback.

**Comment by klotzma** [comment]
Everything works perfectly
Thanks !

**Comment by Pittini** [comment]
You have checked every Datapoint for functionality? Ok, then the device will be now shown as tested and working. Please close if everything is fine.

**Comment by klotzma** [comment]
Yes i checked all. Thanks.
