### ISSUE TITLE
Support Smartmi Airpurifier P1

### ISSUE THREAD

**Issue by Trrw** [Pittini/iobroker-nodemihome#30]
Hello,

can you add the Support for the Smartmi Airpurifier P1?

https://www.smartmiglobal.com/pages/smartmi-air-purifier-p1

Thank you so much!

**Comment by Pittini** [comment]
Can you control it via mihome App? If not - not, if yes we can try.

**Comment by Pittini** [comment]
No answer, no support, I'll close now.
