### ISSUE TITLE
Support for AirPurifier 2

### ISSUE THREAD

**Issue by ApolloSK** [Pittini/iobroker-nodemihome#34]
Hi, can you Support the AirPurifier 2?

I can controll it via mihome App.

Maybe this helps:

  "model": "zhimi.airpurifier.m1",
  "permitLevel": 16,
  "isOnline": true,
  "spec_type": "urn:miot-spec-v2:device:air-purifier:0000A007:zhimi-m1:1",
  
Thank You

**Comment by Pittini** [comment]
Testintegration accomplished, please test with 0.2.18 and report. Dont forget to copy the neccesary Definitionfile as described in readme.

**Comment by Pittini** [comment]
No answer, no service. Closed.

**Comment by ApolloSK** [comment]
Hallo Pittini, 
ich bin leider erst jetzt zum testen gekommen. Ich habe alle enbtsprechend deiner Anleitung installiert.
Leider erhalte ich folgenden Fehler:

12.3.2022, 16:14:00.587	[info ]: javascript.0 (1156) Start javascript script.js.Xiaomi_Miio_Skript
12.3.2022, 16:14:00.709	[error]: javascript.0 (1156) script.js.Xiaomi_Miio_Skript: /opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/devices/zhimi.airpurifier.m1.js:7
12.3.2022, 16:14:00.727	[error]: javascript.0 (1156)     at script.js.Xiaomi_Miio_Skript:3:16
12.3.2022, 16:14:00.728	[error]: javascript.0 (1156)     at script.js.Xiaomi_Miio_Skript:1190:3
12.3.2022, 16:14:00.729	[info ]: javascript.0 (1156) script.js.Xiaomi_Miio_Skript: Starting AllMyMi V.0.2.29
12.3.2022, 16:14:00.750	[info ]: javascript.0 (1156) script.js.Xiaomi_Miio_Skript: registered 0 subscriptions and 0 schedules
12.3.2022, 16:14:00.759	[error]: javascript.0 (1156) script.js.Xiaomi_Miio_Skript: TypeError: Cannot read property 'miioProtocol' of undefined
12.3.2022, 16:14:00.760	[error]: javascript.0 (1156)     at Init (script.js.Xiaomi_Miio_Skript:865:12)
12.3.2022, 16:14:00.761	[error]: javascript.0 (1156)     at script.js.Xiaomi_Miio_Skript:37:1
12.3.2022, 16:14:00.762	[error]: javascript.0 (1156)     at script.js.Xiaomi_Miio_Skript:1190:3

Hast du eine Idee, wo das Problem liegt?

DANKE!
