### ISSUE TITLE
speed_level des S2 geht bis 100

### ISSUE THREAD

**Issue by Fritzelspitze** [Pittini/iobroker-nodemihome#36]
Mit der neuen Version des Scripts geht das speed_level bis 100. Ich habe dann im Script in Zeile 355 max: auf 100 gesetzt und die Range des Objekts ebenfalls auf 1 - 100 gestellt, dann gings wieder.

**Comment by Pittini** [comment]
Ok, max is klar, aber was meinst Du mit Range des Objekts?

**Comment by Fritzelspitze** [comment]
Datda :)
![XiamoSpeed](https://user-images.githubusercontent.com/82735748/123956883-788be080-d9ab-11eb-858a-5e27741225c2.PNG)

**Comment by Pittini** [comment]
Aso, ja klar, aber das is nur nötig wenns schon vorhanden ist, einfach löschen wär auch gegangen, wär dann neu angelegt worden. Wenns dann jetzt passt bitte hier zu machen.
