### ISSUE TITLE
Versionierung über git anstatt über "Dateinamen" + TAGS für releases

### ISSUE THREAD

**Issue by systemofapwne** [Pittini/iobroker-nodemihome#39]
Moin,

ich wollte anmerken, dass eine manuelle Versionierung über "Dateiname-<Version>.js" mit git unnötig ist. Es wird sogar als bad practice angesehen. 
Allgemeine Epfehlung: Ein unveränderlicher Dateiname wie "AllMyMi.js" und die Versionierung einfach git überlassen. Wenn dann ein neuer Versionssprung erreicht ist: Den commit in github TAGgen. Dann kann man ganz einfach zwischen den Versionen hin und her wechseln. Und wenn sich noch ein paar Sekunden mehr Zeit nimmt: Neben den TAG gleich ein Release erstellen -> 1 click download der Version, die man haben möchte ;)

**Comment by Pittini** [comment]
Werd ich mir mal anschaun, war schon froh VS Code erfolgreich mit Git verbunden zu haben und hab auch viele Anfänger User die mit Git eh oft ein Problem haben und nich wissen wie se an den Code kommen, für die hat das in meiner Variante immer gut gepasst. Was ich auch nich weis, wäre wie die Git Version dann in mein Skript kommt, da dieses sich ja beim starten mit seiner Version meldet, was ich wiederum brauch um bei Issues zu sehen welche (evtl. uralte) Version der Meldende so nutzt. Aber danke für den Hinweis.

**Comment by Pittini** [comment]
So, sollte jetzt passen, ich mach ma zu.
