### ISSUE TITLE
Air Purifier 3H wird gefunden, aber keine Daten mehr

### ISSUE THREAD

**Issue by Bender275** [Pittini/iobroker-nodemihome#45]
Hallo Pittini,

ich habe das Problem, dass mein 3H Luftreiniger vom Skript aus der Cloud gelesen werden kann, aber keine Werte übermittelt werden.
In der App geht alles. Vor einiger Zeit ging auch alles (mit Skript 0.2.23), plötzlich aber nicht mehr. Habe das aktuelle Skript geladen, Node-mihome neu installiert, die Def-Datei neu reinkopiert - keine Besserung.

Versuche ich, den 3H über Google einzuschalten, kommt:
javascript.0 | 2021-09-27 09:33:00.618 | error | (3712) Error: Call to device timed out     at Timeout.retry [as _onTimeout]  (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/protocol-miio.js:358:23)     at listOnTimeout (
javascript.0 | 2021-09-27 09:33:00.618 | error | (3712) Error: Call to device timed out

Ich weiß nicht mehr genaus, seit wann es nicht mehr geht; evtl. habe ich node-js und den js-controller aktualisiert, aber spätestens das Neuladen der node-mihome und des Skripts sollte eventuelle Probleme beheben, oder?

Danke!

**Comment by Pittini** [comment]
> Ich weiß nicht mehr genaus, seit wann es nicht mehr geht; evtl. habe ich node-js und den js-controller aktualisiert, aber spätestens das Neuladen der node-mihome und des Skripts sollte eventuelle Probleme beheben, oder?

Nach aktualisierung des JS Controllers müssen die Def Dateien neu einkopiert werden, haste das gemacht?

**Comment by Bender275** [comment]
Ja, die Datei ist aktuell:
![grafik](https://user-images.githubusercontent.com/91456066/134870946-96470931-bbf2-4388-bbc5-b1f7fd7fbf6f.png)

**Comment by Bender275** [comment]
Ich weiß nicht warum, aber auf einmal geht es wieder. Gemacht habe ich nichts, war Mittagessen holen... Egal, danke!
