### ISSUE TITLE
zhimi.humidifier.ca4 keine Werte

### ISSUE THREAD

**Issue by tobasium** [Pittini/iobroker-nodemihome#46]
Hallo Zusammen,

das Gerät lässt sich nicht steuern. die Werte buzzer bis temperature bekommen keine Werte: (null)
die Info Werte funktionieren
Gibt es hier schon einen Ansatz.

**Comment by Pittini** [comment]
@tobasium Jo, mag sein, is ja auch als untested bzw. ready to test deklariert. Sowas passiert meist wenn wer nen Gerät wünscht und dann kein Bock auf testen und Feedback hat wenns nich gleich klappt. Können wir aber gern angehen wennde Bock auf testen hast? Die erste frage wäre: Hast Du die Def Datei kopiert wie in der Anleitung beschrieben?

**Comment by tobasium** [comment]
Hallo,

klar bin ich bereit zu testen. Datei wurde kopiert.

**Comment by Pittini** [comment]
Ok, prima.  Mir is grad was aufgefallen, als erstes testest bitte mal folgendes: In der Def Datei findest diesen Block: 

```
  this._propertiesToMonitor = [
      'limit_hum',
      'power',
      'humidity',
      'temperature',
      'buzzer',
      'led',
      'depth',
      'dry',
      'child_lock',
      'mode',
    ];
  }
```
hier bitte das Komma nach 'mode' entfernen. Speichern. JS Controller neustarten. Guggen ob was geht. Wenn nein, machste aus dem Block folgendes, also alles raus bis auf power, den Punkt gibts sicher:

```
  this._propertiesToMonitor = [
      'power'
          ];
  }
```


Immer dran denken, nach jeder Änderung der Def Datei den JS Controller neuzustarten. Wenns mit power klappen sollte, dann nimmste Punkt für Punkt wieder rein, bisses nimmer geht, dann weiste wer der Bösewicht ist. Wenn auch power schon gar nicht gehen sollte, bitte melden, dann muß ich das andere Protokoll nehmen, da muß  aber ich dannnerst mal ran.

**Comment by tobasium** [comment]
Hi,

Leider geht schon Power nicht. Habe es mal kurz getestet. Ganzen IO neu gestartet.

**Comment by Pittini** [comment]
Ok, dann mal das andere Protokoll. Bitte sowohl Skript als auch Dev Datei neu holen (aus der develop branch) und testen. Ich hab nur power rein, das muß jetzt dann eigentlich klappen.

**Comment by tobasium** [comment]
Ich teste das heute Abend und gebe dann Feedback.

Vielen Dank schonmal.

**Comment by tobasium** [comment]
Hi,

ich hab es jetzt getestet. Unterordner wurde erstellt mit humidifier, Wert on funktioniert. 
info Ordner scheinen auch alle Werte zu gehen.

**Comment by Pittini** [comment]
Ok, dann mal volles Programm, neue Version und Def Datei bitte wieder aus der Dev Branch und testen. Bitte auch immer nicht nur testen ob Werte kommen, sondern auch ob Werte gesetzt werden können.

**Comment by tobasium** [comment]
Hallo,

ich habe es getestet. Folgendes Feedback. 
Script getauscht und Definitionsdatei getauscht.
An und Ausschalten funktioniert. Rückmeldung an den Datenpunkt aber nicht mehr. Habe den Fehler auch in der Definitionsdatei ausgemacht. Nutze ich die von unserem ersten Test kann ich die Werte schalten und bekomme auch die Rückmeldung vom Gerät bestätigt.

Alle anderen Werte werden zwar angelegt aber nicht befüllt. (Ausnahme Info Ordner)

Hoffe es passt so vom erklären sonst gerne auch mal Discord / Teams oder Teamspeak.

**Comment by Pittini** [comment]
Ich hab mir grad die Def noch mal angeguggt und tatsächlich nen Fehler gefunden, da hat sich ein Punkt statt nem Doppelpunkt eingeschlichen und zwar hier:      ` 'physical-controls-locked:physical-controls-locked',`

Sollte es dann immer noch nicht klappen, mußt Eintrag für Eintrag ich der Def Datei checken, wie im ersten Post schon beschrieben.

**Comment by tobasium** [comment]
das sieht soweit gut aus. Alle Werte werden aktuell sauber gezogen.
Ich kann aktuell keine Probleme feststellen.

Vielen Dank. Ich werde morgen noch das steuern einzelner Werte testen. AN und Aus geht.

Ich hab auch noch eine yeelink.light.bslamp2 falls du die implementieren möchtest.

**Comment by Pittini** [comment]
Hi, morgen is seit ner Woche vorbei, wie ist der Stand? Is die Bslamp nicht bluetooth? Das geht nämlich dann nicht, nur Wlan Devices atm.

**Comment by tobasium** [comment]
Hi,

sorry war geschäftlich wieder mal unterwegs. Mir sind keine Probleme aufgefallen. Es läuft alles.

Bslamp ist wifi.

**Comment by tobasium** [comment]
All working good
