### ISSUE TITLE
Integrate fengmi.projector.fm15

### ISSUE THREAD

**Issue by Pittini** [Pittini/iobroker-nodemihome#47]
Basic Integration  fengmi.projector.fm15 aka mijia laser TV

**Comment by Pittini** [comment]
Bitte die Def Datei fengmi.projector.fm15.js von hier: https://github.com/Pittini/iobroker-nodemihome/tree/develop/DefinitionfilesForNode-Mihome ins node-mihome Verzeichnis kopieren wie in der Anleitung beschrieben.
Dann das aktuelle Skript aus der develop branche installieren. Testen ob power angezeigt wird und/oder sich bedienen lässt. DAnn bitte Feedback hier. (Erfolgschance ist 50% da es 2 mögliche Protokolle gibt.)

**Comment by Cheesys** [comment]
<html>
<body>


09:37:32.012 | error | javascript.0 (6397) script.js.Mi_Beamer: Error: Model fengmi.projector.fm15 is not supported
-- | -- | --
09:37:32.013 | error | javascript.0 (6397) at CreateDevices (script.js.Mi_Beamer:842:36)
09:37:32.014 | error | javascript.0 (6397) at main (script.js.Mi_Beamer:774:11)


</body>
</html>

bekomme ich bei skriptstart

**Comment by Pittini** [comment]
@Cheesys Kann eigentlich nich sein. Hast Du das richtige Skript? Welches Datum steht oben im Skript? Def Datei kopiert?

**Comment by Cheesys** [comment]
<html>
<body>


18:29:21.240 | info | javascript.0 (9671) script.js.Mi_Beamer: Mijia Laser TV
-- | -- | --
18:29:21.240 | info | javascript.0 (9671) script.js.Mi_Beamer: Now searching for supported Devices...
18:29:21.241 | info | javascript.0 (9671) script.js.Mi_Beamer: Device Mijia Laser TV is supported, creating DataPoints
18:29:21.253 | info | javascript.0 (9671) script.js.Mi_Beamer: Now creating device for fengmi.projector.fm15 / mitv.cfbb32eee9abea70dd3a536b25dbc42b:aaa931fda4494926ba4c9098f2348ecd / 192.168.50.148 / 35333934443230423843463731353733 / 10000
18:29:21.253 | info | javascript.0 (9671) script.js.Mi_Beamer: Created device {"_events":{},"_eventsCount":0,"_maxListeners":100,"id":"mitv.cfbb32eee9abea70dd3a536b25dbc42b:aaa931fda4494926ba4c9098f2348ecd","address":"192.168.50.148","token":"35333934443230423843463731353733","protocol":"local","refresh":10000,"_properties":{},"_propertiesToMonitor":["power"],"_miotSpec":null,"_miotSpecType":null,"model":"fengmi.projector.fm15","setter":{},"definition":{"info":[{"id":"localip","initial":"","forceCreation":false,"common":{"read":true,"write":true,"name":"Ip Adress","type":"string","role":"value","def":""}},{"id":"token","initial":"","forceCreation":false,"common":{"read":true,"write":true,"name":"Token","type":"string","role":"value","def":""}},{"id":"did","initial":"","forceCreation":false,"common":{"read":true,"write":true,"name":"Device Id","type":"string","role":"value","def":""}},{"id":"model","initial":"","forceCreation":false,"common":{"read":true,"write":true,"name":"Model","type":"string","role":"value","def":""}},{"id":"rssi","initial":0,"forceCreation":false,"common":{"read":true,"write":false,"name":"rssi","type":"number","role":"value.rssi","def":0}},{"id":"name","initial":"","forceCreation":false,"common":{"read":true,"write":true,"name":"Name","type":"string","role":"value","def":""}},{"id":"isOnline","initial":false,"forceCreation":false,"common":{"read":true,"write":true,"name":"Is online","type":"boolean","role":"value","def":false}}],"model":"fengmi.projector.fm15","description":"Mijia Laser TV","setter":{},"common":[{"name":"power","role":"switch","write":true,"read":true,"type":"boolean"}]},"firstrun":true,"rssi":0,"isOnline":true} now fetching data
18:29:25.256 | info | javascript.0 (9671) script.js.Mi_Beamer: Init Device# 0 - device="fengmi.projector.fm15"
18:29:25.256 | info | javascript.0 (9671) script.js.Mi_Beamer: Setting trigger #0 for fengmi.projector.fm15


</body>
</html>

Sorry hab es falsch kopiert
kriege so jetzt den Status zurück jedoch keine Änderung, muss dafür jedesmal das Skript neu starten

**Comment by Cheesys** [comment]
Das stand noch im log aber war vermutlich bevor ich die Def Datei kopiert habe

<html>
<body>


javascript.0 | 2021-10-25 17:31:40.275 | error | FetchError: network timeout at: https://api.io.mi.com/app/home/device_list at Timeout.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-fetch/lib/index.js:1476:13) at listOnTimeout (internal/timers.js:554:17) at processTimers (internal/timers.js:497:7)
-- | -- | -- | --
javascript.0 | 2021-10-25 17:31:40.275 | error | Error: network timeout at: https://api.io.mi.com/app/home/device_list
javascript.0 | 2021-10-25 17:31:40.275 | error | An error happened which is most likely from one of your scripts, but the originating script could not be detected.
javascript.0 | 2021-10-25 17:31:30.275 | error | FetchError: network timeout at: https://api.io.mi.com/app/home/device_list at Timeout.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-fetch/lib/index.js:1476:13) at listOnTimeout (internal/timers.js:554:17) at processTimers (internal/timers.js:497:7)
javascript.0 | 2021-10-25 17:31:30.274 | error | Error: network timeout at: https://api.io.mi.com/app/home/device_list
javascript.0 | 2021-10-25 17:31:30.274 | error | An error happened which is most likely from one of your scripts, but the originating script could not be detected.


</body>
</html>

**Comment by Pittini** [comment]
> kriege so jetzt den Status zurück jedoch keine Änderung, muss dafür jedesmal das Skript neu starten

Jo, das is soweit normal solang das Gerät nich richtig eingerichtet ist. Wenn bei der Variante jetzt, nix zurückkommt, hab ich Dir mal Variante2 fertig gemacht....same procedure.
Hab jetzt aber den volume Datenpunkt genommen - aus Gründen. Schau mal ob da jetzt was zurückkommt.
Und nich vergessen den JS Controller nach update der Def Datei neu zu starten.

**Comment by Cheesys** [comment]
<html>
<body>


17:44:30.032 | error | javascript.0 (12727) script.js.Mi_Beamer: Error: Pls login before make any request
-- | -- | --
17:44:30.037 | error | javascript.0 (12727) at Init (script.js.Mi_Beamer:806:50)


</body>
</html>

kommt jetzt direkt
login daten stimmen aber bzw. wurden nicht geändert

**Comment by Pittini** [comment]
Da dran wurde ja nix geändert, kontrollier alles und starte mal den JS Controller neu.

**Comment by Cheesys** [comment]
alles neu gestartet / adguard deaktiviert / vpn deaktiviert / datei erneut kopiert

<html>
<body>


20:53:39.503 | error | javascript.0 (9778) script.js.Mi_Beamer: TypeError: Cannot read property 'forEach' of undefined
-- | -- | --
20:53:39.505 | error | javascript.0 (9778) at CreateDevices (script.js.Mi_Beamer:856:17)
20:53:39.505 | error | javascript.0 (9778) at main (script.js.Mi_Beamer:774:5)


</body>
</html>

**Comment by Pittini** [comment]
Sorry, aber das dürfte ein Problem bei Dir sein, such mal weiter ich kann da nix machen. Wenn Du das mit dem testen nich hinkriegst müssen wir leider abbrechen.

**Comment by Cheesys** [comment]
Servus, bin gerade leider viel unterwegs aber werde heute bzw. morgen nochmal alles neu aufsetzen und testen
EDIT:
so eben nochmal getestet selber Fehler wie vor 5 Tagen.
Als Test nochmal die Def Datei vom 22.10 eingefügt -> Skript ohne Fehler und Status wird richtig angezeigt nach jedem javascript neustart

**Comment by Pittini** [comment]
Sorry für die späte Antwort, aber edits werden nicht gemeldet, deswegen hatte ich die Antwort nich mitgekriegt.
Wenn beide Varianten nicht klappen, klappts wohl nicht mit dem Gerät, warum auch immer.
