### ISSUE TITLE
Error during LogIn

### ISSUE THREAD

**Issue by FreunderNacht** [Pittini/iobroker-nodemihome#48]
Hello,
since I updated the web adapter (at least that's when I noticed it), the script no longer runs or I get error messages:

`23.10.2021, 23:07:18.273	[info ]: javascript.0 (959) Stop script script.js.Mi_Home
23.10.2021, 23:07:18.285	[info ]: javascript.0 (959) Start javascript script.js.Mi_Home
23.10.2021, 23:07:18.303	[info ]: javascript.0 (959) script.js.Mi_Home: Starting AllMyMi V.0.2.25
23.10.2021, 23:07:18.309	[info ]: javascript.0 (959) script.js.Mi_Home: registered 0 subscriptions and 0 schedules
23.10.2021, 23:07:18.845	[info ]: javascript.0 (959) script.js.Mi_Home: You are already logged in, login canceled
23.10.2021, 23:07:18.845	[info ]: javascript.0 (959) script.js.Mi_Home: Retrieving your in de registered MiHome Devices
23.10.2021, 23:07:18.846	[error]: javascript.0 (959) script.js.Mi_Home: Error: Pls login before make any request
23.10.2021, 23:07:18.847	[error]: javascript.0 (959)     at Init (script.js.Mi_Home:802:50)`

<html>
<body>

javascript.0 | 2021-10-23 23:07:18.848 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- | -- | -- | --
javascript.0 | 2021-10-23 23:07:18.847 | error | at runMicrotasks (<anonymous>)
javascript.0 | 2021-10-23 23:07:18.847 | error | at Init (script.js.Mi_Home:802:50)
javascript.0 | 2021-10-23 23:07:18.847 | error | at MiCloudProtocol.getDevices (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/protocol-micloud.js:121:29)
javascript.0 | 2021-10-23 23:07:18.847 | error | at MiCloudProtocol.request (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/protocol-micloud.js:67:13)
javascript.0 | 2021-10-23 23:07:18.846 | error | script.js.Mi_Home: Error: Pls login before make any request
javascript.0 | 2021-10-23 23:07:18.845 | info | script.js.Mi_Home: Retrieving your in de registered MiHome Devices
javascript.0 | 2021-10-23 23:07:18.845 | info | script.js.Mi_Home: You are already logged in, login canceled
javascript.0 | 2021-10-23 23:07:18.309 | info | script.js.Mi_Home: registered 0 subscriptions and 0 schedules
javascript.0 | 2021-10-23 23:07:18.303 | info | script.js.Mi_Home: Starting AllMyMi V.0.2.25
javascript.0 | 2021-10-23 23:07:18.285 | info | Start javascript script.js.Mi_Home

</body>
</html>

![image](https://user-images.githubusercontent.com/69077006/138572135-99fe8be7-c120-49f5-b501-c943b0eab564.png)

I am currently using the web adapter version 3.4.9 and ScriptVersion = "0.2.25".

**Comment by Pittini** [comment]
Have you tried to restart the JS Controller or the complete System? There are no known Issues together with the Web Adapter.

**Comment by FreunderNacht** [comment]
Yes, I have already restarted both the js controller and the whole system.
________________________________


________________________________
Von: Pittini ***@***.***>
Gesendet: Sonntag, 24. Oktober 2021 09:39
An: Pittini/iobroker-nodemihome
Cc: Armin Heinz; Author
Betreff: Re: [Pittini/iobroker-nodemihome] Error during LogIn (Issue #48) 

Have you tried to restart the JS Controller or the complete System? There are no known Issues together with the Web Adapter.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Bender275** [comment]
Hatte das gleiche Problem vor ein paar Tagen. Ich merkte dann, dass die Device Definitionsdatei weg war. Habe sie neu reinkopiert, alles neu gestartet. Fehler ist jetzt:
<html><body>


javascript.0 | 2021-11-04 11:00:56.684 | error | at script.js.Räume.Wohnen.Xiaomi_0_2_25:1114:3
-- | -- | -- | --
javascript.0 | 2021-11-04 11:00:56.684 | error | at script.js.Räume.Wohnen.Xiaomi_0_2_25:34:1
javascript.0 | 2021-11-04 11:00:56.683 | error | at Init (script.js.Räume.Wohnen.Xiaomi_0_2_25:791:12)
javascript.0 | 2021-11-04 11:00:56.683 | error | script.js.Räume.Wohnen.Xiaomi_0_2_25: TypeError: Cannot read property 'miioProtocol' of undefined
javascript.0 | 2021-11-04 11:00:56.682 | info | script.js.Räume.Wohnen.Xiaomi_0_2_25: registered 0 subscriptions and 0 schedules
javascript.0 | 2021-11-04 11:00:56.676 | info | script.js.Räume.Wohnen.Xiaomi_0_2_25: Starting AllMyMi V.0.2.25


</body>
</html>

**Comment by Pittini** [comment]
@Bender275 Wenn Du nich sagst um welches Gerät es geht.... Auf jeden Fall is die 0.2.25 zwar stable aber nicht aktuell, kommt jetzt also drauf an welches Gerät Du hast. Versuch mal die 0.2.26

**Comment by Bender275** [comment]
Sorry, ist ein Air Purifier 3H.

Ich bin gerade blind - wo finde ich die 0.2.26? Weder unter Admin, noch Develop finde ich was, und AllMyMi.js ist 0.2.25...

**Comment by Pittini** [comment]
> Ich bin gerade blind - wo finde ich die 0.2.26?

Unter Tags, gleich neben Branch.

**Comment by Bender275** [comment]
Danke!

So, habe nun 0.2.26 "installiert" und die dabei mitgelieferten Definitionsdateien nochmal reingeladen.
Was mir auffällt: Die zhimi.airpurifier.mb3.js war mal (im September) 199 KB groß, jetzt nur noch 3 KB...

Ich habe jetzt auch einen anderen Fehler:
<html><body>


17:07:54.685 | info | javascript.0 (696) Start javascript script.js.Räume.Wohnen.Xiaomi_0_2_26
-- | -- | --
17:07:54.693 | info | javascript.0 (696) script.js.Räume.Wohnen.Xiaomi_0_2_26: Starting AllMyMi V.0.2.25
17:07:54.699 | info | javascript.0 (696) script.js.Räume.Wohnen.Xiaomi_0_2_26: registered 0 subscriptions and 0 schedules
17:07:54.996 | info | javascript.0 (696) script.js.Räume.Wohnen.Xiaomi_0_2_26: You are already logged in, login canceled
17:07:54.996 | info | javascript.0 (696) script.js.Räume.Wohnen.Xiaomi_0_2_26: Retrieving your in de registered MiHome Devices
17:07:54.997 | error | javascript.0 (696) script.js.Räume.Wohnen.Xiaomi_0_2_26: Error: Pls login before make any request
17:07:54.998 | error | javascript.0 (696)     at Init (script.js.Räume.Wohnen.Xiaomi_0_2_26:800:50)


</body>
</html>

**Comment by rowdy238** [comment]
Hi,

hab das gleiche Problem.
Pi und JS Controller neugestartet, jedoch ohne Erfolg...

Edit: Bei mir steht es auch in keinem Zusammenhang mit dem Update eines Adapters im iobroker oder Ähnlichem.
Das Einzige was heute geupdatet wurde war der Pi (sudo apt-get full-upgrade) da gab´s nen paar Kernel & Bootloader Updates, sonst nichts.

Log:


javascript.0 | 2021-11-05 10:13:52.867 | error | at processTicksAndRejections (internal/process/task_queues.js:95:5)
-- | -- | -- | --
javascript.0 | 2021-11-05 10:13:52.866 | error | at runMicrotasks (<anonymous>)
javascript.0 | 2021-11-05 10:13:52.866 | error | at Init (script.js.Yvonne.Xiaomi_Geräte.Xiaomi:800:50)
javascript.0 | 2021-11-05 10:13:52.865 | error | at MiCloudProtocol.getDevices  (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/protocol-micloud.js:121:29)
javascript.0 | 2021-11-05 10:13:52.865 | error | at MiCloudProtocol.request  (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/protocol-micloud.js:67:13)
javascript.0 | 2021-11-05 10:13:52.864 | error | script.js.Yvonne.Xiaomi_Geräte.Xiaomi: Error: Pls login before make any request

**Comment by Pittini** [comment]
@Bender275 @FreunderNacht : Verwendet Ihr auch nen Pi?

**Comment by Bender275** [comment]
Ja, nen Raspi 4. Alles aktuell, Node.js 12.22.7, zur Sicherheit npm install node-mihome gemacht, im JS-Adapter als zusätzliches Modul eingetragen und SetObject erlaubt.

**Comment by FreunderNacht** [comment]
Hi,
bei mir läuft der IOBroker auf einer Proxmox VM.
Node.js ist auch 12.22.7.

**Comment by Pittini** [comment]
Ich weis dass das sehr unerquicklich ist, aber ich kann das Problem weder reproduzieren (verwende nen Nuc mit Proxmox) noch mir erklären. Das einzige was ich weis, ist, dass bisher immer wenn solche Meldungen kamen iwas an den Installationen nicht gepasst hat, bei einigen Pi Nutzern blieb es ergebnislos. Leider sind das alles Probleme der node-mihome dessen Dev leider inaktiv ist. Mein Skript macht ja qu8asi nur ne "Übersetzung", alle Daten, Logins etc. gehen durch die node-mihome. Falls die mit irgendwas neuerem nicht kompatibel sein sollte.....wärs richtig Ka**e. Soll heißen, ich kann Euch hier keine Hilfestellung geben, evtl. kommt Ihr selber drauf an wasses hängt.

**Comment by e-i-k-e** [comment]
Abend,

ich erhalte auch seit einiger Zeit die folgende Meldung.
Intel NUC mit Proxmox, ioBroker läuft unter Ubuntu 20.04 im Container.
Alle Adapter sind auf aktueller Version (Beta)



<html>
<body>


javascript.0 | 2021-11-05 23:15:18.738 | error | (19539) at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- | -- | -- | --
javascript.0 | 2021-11-05 23:15:18.738 | error | (19539) at runMicrotasks (<anonymous>)
javascript.0 | 2021-11-05 23:15:18.738 | error | (19539) at Init (script.js.common.iobroker-nodemihome:795:50)
javascript.0 | 2021-11-05 23:15:18.738 | error | (19539) at MiCloudProtocol.getDevices (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/protocol-micloud.js:121:29)
javascript.0 | 2021-11-05 23:15:18.737 | error | (19539) at MiCloudProtocol.request (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/protocol-micloud.js:67:13)
javascript.0 | 2021-11-05 23:15:18.736 | error | (19539) script.js.common.iobroker-nodemihome: Error: Pls login before make any request
javascript.0 | 2021-11-05 23:15:18.731 | info | (19539) script.js.common.iobroker-nodemihome: Retrieving your in de registered MiHome Devices
javascript.0 | 2021-11-05 23:15:18.730 | info | (19539) script.js.common.iobroker-nodemihome: You are already logged in, login canceled
javascript.0 | 2021-11-05 23:15:16.183 | info | (19539) script.js.common.iobroker-nodemihome: registered 0 subscriptions and 0 schedules
javascript.0 | 2021-11-05 23:15:16.146 | info | (19539) script.js.common.iobroker-nodemihome: Starting AllMyMi V.0.2.25
javascript.0 | 2021-11-05 23:15:16.002 | info | (19539) Start javascript script.js.common.iobroker-nodemihome


</body>
</html>




`<html>
<body>


23:15:16.146 | info | javascript.0 (19539) script.js.common.iobroker-nodemihome: Starting AllMyMi V.0.2.25
-- | -- | --
23:15:16.183 | info | javascript.0 (19539) script.js.common.iobroker-nodemihome: registered 0 subscriptions and 0 schedules
23:15:18.730 | info | javascript.0 (19539) script.js.common.iobroker-nodemihome: You are already logged in, login canceled
23:15:18.731 | info | javascript.0 (19539) script.js.common.iobroker-nodemihome: Retrieving your in de registered MiHome Devices
23:15:18.736 | error | javascript.0 (19539) script.js.common.iobroker-nodemihome: Error: Pls login before make any request
23:15:18.738 | error | javascript.0 (19539) at Init (script.js.common.iobroker-nodemihome:795:50)


</body>
</html>`


Was mir auch aufgefallen ist, dass die Datei "zhimi.airpurifier.vb2.js" oft nach einem Neustart nicht mehr vorhanden ist und ich diese erneut hinzufügen muss.

**Comment by rowdy238** [comment]
Hi Pittini,

ich meine mich zu erinnern, dass ich, vor geraumer Zeit, auch mal statt "node-mihome" alternativ "pittini-node-mihome" 
eingetragen hatte.

**Wenn das Probem bei uns an der node-mihome liegt:**
Gibts es, wenn der Dev von node-mihome nicht mehr aktiv ist, evtl. eine Alternative die du wieder bereitstellen könntest?
DAS wäre super!

**Comment by Pittini** [comment]
> Hi Pittini,
> 
> ich meine mich zu erinnern, dass ich, vor geraumer Zeit, auch mal statt "node-mihome" alternativ "pittini-node-mihome" eingetragen hatte.

Ja, das hatten wir mal versucht, hat zwar bei wenigen geklappt, bei den meisten aber noch mehr Probleme verursacht, deswegen ersatzlos gestrichen.
> 
> **Wenn das Probem bei uns an der node-mihome liegt:** Gibts es, wenn der Dev von node-mihome nicht mehr aktiv ist, evtl. eine Alternative die du wieder bereitstellen könntest? DAS wäre super!

Mir ist absolut nichts bekannt was die node-mihome ersetzen könnte. Sicher könnte man nen Fork machen, fixen und als neues npm Modul raushaun, aber ganz ehrlich, dafür reichen meine Skills nicht.

**Comment by Bender275** [comment]
> Was mir auch aufgefallen ist, dass die Datei "zhimi.airpurifier.vb2.js" oft nach einem Neustart nicht mehr vorhanden ist und ich diese erneut hinzufügen muss.

Genau das ist mir auch aufgefallen (bei  mir ist es die zhimi.airpurifier.mb3.js, aber egal).

@Pittini 
Mit der 3-KB-zhimi.airpurifier.mb3.js kommt die Meldung mit Pls login, mit der 199-KB-zhimi.airpurifier.mb3.js kommt

<html><body>


0:29:39.620 | info | javascript.0 (13391) Stop script script.js.Räume.Wohnen.Xiaomi_0_2_26
-- | -- | --
20:29:39.651 | info | javascript.0 (13391) Start javascript script.js.Räume.Wohnen.Xiaomi_0_2_26
20:29:39.701 | error | javascript.0  (13391) script.js.Räume.Wohnen.Xiaomi_0_2_26:  /opt/iobroker/node_modules/node-mihome/lib/devices/zhimi.airpurifier.mb3.js:7
20:29:39.709 | error | javascript.0 (13391)     at script.js.Räume.Wohnen.Xiaomi_0_2_26:3:16
20:29:39.709 | error | javascript.0 (13391)     at script.js.Räume.Wohnen.Xiaomi_0_2_26:1115:3
20:29:39.710 | info | javascript.0 (13391) script.js.Räume.Wohnen.Xiaomi_0_2_26: Starting AllMyMi V.0.2.25
20:29:39.713 | info | javascript.0 (13391) script.js.Räume.Wohnen.Xiaomi_0_2_26: registered 0 subscriptions and 0 schedules
20:29:39.714 | error | javascript.0 (13391) script.js.Räume.Wohnen.Xiaomi_0_2_26: TypeError: Cannot read property 'miioProtocol' of undefined
20:29:39.714 | error | javascript.0 (13391)     at Init (script.js.Räume.Wohnen.Xiaomi_0_2_26:791:12)
20:29:39.715 | error | javascript.0 (13391)     at script.js.Räume.Wohnen.Xiaomi_0_2_26:36:1
20:29:39.715 | error | javascript.0 (13391)     at script.js.Räume.Wohnen.Xiaomi_0_2_26:1115:3


</body>
</html>

Welche ist Definitionsdatei die richtige? Vielleicht kann man es erstmal so eingrenzen. Ich habe sie mal als TXT angehängt.
[zhimi.airpurifier.mb3_199.txt](https://github.com/Pittini/iobroker-nodemihome/files/7491125/zhimi.airpurifier.mb3_199.txt)

**Comment by Pittini** [comment]
> Welche ist Definitionsdatei die richtige?

Die richtige ist die kleine mit 3kb. Die andere mit 199 ist schlichtweg falsch runtergeladen, nämlich als html Seite, sieht man aufn ersten Blick wenn man reinschaut.

**Comment by rowdy238** [comment]
Hi.

also bei mir funktioniert jetzt wieder alles tadellos.
Habe festgestellt das es (zumindest bei iOS) ein Update der Xiaomi-App gab.
Dort musste ich mich erneut einloggen auf dem Handy.

Da dachte ich, hmm... evtl. hat das ja auch was mit dem Fehler zu tun und hab das Script erneut gestartet und siehe da, es funzt wieder wie gewünscht.

Evtl. hilft das ja dem Ein oder Anderen hier.
Schaut mal nach aufm Handy ;)

**Comment by Bender275** [comment]
> 
> 
> Hi.
> 
> also bei mir funktioniert jetzt wieder alles tadellos. Habe festgestellt das es (zumindest bei iOS) ein Update der Xiaomi-App gab. Dort musste ich mich erneut einloggen auf dem Handy.
> 
> Da dachte ich, hmm... evtl. hat das ja auch was mit dem Fehler zu tun und hab das Script erneut gestartet und siehe da, es funzt wieder wie gewünscht.
> 
> Evtl. hilft das ja dem Ein oder Anderen hier. Schaut mal nach aufm Handy ;)

Super, vielen Dank für den Tipp! Ich musste die App erstmal wieder installieren, aber nachdem ich mich da neu angemeldet hatte, funktioniert auch das Skript wieder. Es schmeißt zwar immer wieder ein paar Fehler, aber egal, solange es funktioniert.

Danke an alle für die Unterstützung!

**Comment by Bender275** [comment]
Hilfe, seitdem wird jedoch mein Log geflutet. Ich habe im 5 bis 10 Minuten Rythmus folgende Einträge:

<html><body>


javascript.0 | 2021-11-08 10:20:33.765 | warn | script.js.Räume.Wohnen.Xiaomi_0_2_26: Empty packet for use-time.use-time, skipping refresh
-- | -- | -- | --
javascript.0 | 2021-11-08 10:20:33.765 | warn | script.js.Räume.Wohnen.Xiaomi_0_2_26: Empty packet for motor-speed.favorite-fan-level, skipping refresh
javascript.0 | 2021-11-08 10:20:33.764 | warn | script.js.Räume.Wohnen.Xiaomi_0_2_26: Empty packet for motor-speed.motor-set-speed, skipping refresh
javascript.0 | 2021-11-08 10:20:33.764 | warn | script.js.Räume.Wohnen.Xiaomi_0_2_26: Empty packet for motor-speed.motor-speed, skipping refresh
javascript.0 | 2021-11-08 10:20:33.763 | warn | script.js.Räume.Wohnen.Xiaomi_0_2_26: Empty packet for indicator-light.on, skipping refresh
javascript.0 | 2021-11-08 10:20:33.763 | warn | script.js.Räume.Wohnen.Xiaomi_0_2_26: Empty packet for indicator-light.brightness, skipping refresh
javascript.0 | 2021-11-08 10:20:33.762 | warn | script.js.Räume.Wohnen.Xiaomi_0_2_26: Empty packet for alarm.alarm, skipping refresh
javascript.0 | 2021-11-08 10:20:33.761 | warn | script.js.Räume.Wohnen.Xiaomi_0_2_26: Empty packet for filter.filter-used-time, skipping refresh
javascript.0 | 2021-11-08 10:20:33.761 | warn | script.js.Räume.Wohnen.Xiaomi_0_2_26: Empty packet for filter.filter-life-level, skipping refresh
javascript.0 | 2021-11-08 10:20:33.760 | warn | script.js.Räume.Wohnen.Xiaomi_0_2_26: Empty packet for environment.temperature, skipping refresh
javascript.0 | 2021-11-08 10:20:33.759 | warn | script.js.Räume.Wohnen.Xiaomi_0_2_26: Empty packet for environment.relative-humidity, skipping refresh


</body>
</html>

**Comment by rowdy238** [comment]
@Bender275 
Das hab ich auch, allerdings nicht im 5 Minuten Rythmus.
Ist aber nicht schlimm...nur ne Warnung, kein Error...



javascript.0 | 2021-11-08 10:22:04.041 | warn | script.js.Yvonne.Xiaomi_Geräte.Xiaomi: Empty packet for use-time.use-time, skipping refresh
-- | -- | -- | --
javascript.0 | 2021-11-08 10:22:04.032 | warn | script.js.Yvonne.Xiaomi_Geräte.Xiaomi: Empty packet for motor-speed.favorite-fan-level, skipping refresh
javascript.0 | 2021-11-08 10:22:04.031 | warn | script.js.Yvonne.Xiaomi_Geräte.Xiaomi: Empty packet for motor-speed.motor-set-speed, skipping refresh
javascript.0 | 2021-11-08 10:22:04.031 | warn | script.js.Yvonne.Xiaomi_Geräte.Xiaomi: Empty packet for motor-speed.motor-speed, skipping refresh
javascript.0 | 2021-11-08 10:22:04.031 | warn | script.js.Yvonne.Xiaomi_Geräte.Xiaomi: Empty packet for indicator-light.on, skipping refresh
javascript.0 | 2021-11-08 10:22:04.031 | warn | script.js.Yvonne.Xiaomi_Geräte.Xiaomi: Empty packet for indicator-light.brightness, skipping refresh
javascript.0 | 2021-11-08 10:22:04.030 | warn | script.js.Yvonne.Xiaomi_Geräte.Xiaomi: Empty packet for alarm.alarm, skipping refresh
javascript.0 | 2021-11-08 10:22:04.030 | warn | script.js.Yvonne.Xiaomi_Geräte.Xiaomi: Empty packet for filter.filter-used-time, skipping refresh
javascript.0 | 2021-11-08 10:22:04.029 | warn | script.js.Yvonne.Xiaomi_Geräte.Xiaomi: Empty packet for filter.filter-life-level, skipping refresh
javascript.0 | 2021-11-08 10:22:04.029 | warn | script.js.Yvonne.Xiaomi_Geräte.Xiaomi: Empty packet for environment.temperature, skipping refresh
javascript.0 | 2021-11-08 10:22:04.029 | warn | script.js.Yvonne.Xiaomi_Geräte.Xiaomi: Empty packet for environment.relative-humidity, skipping refresh
javascript.0 | 2021-11-08 10:22:04.028 | warn | script.js.Yvonne.Xiaomi_Geräte.Xiaomi: Empty packet for environment.pm2_5-density, skipping refresh
javascript.0 | 2021-11-08 10:22:04.028 | warn | script.js.Yvonne.Xiaomi_Geräte.Xiaomi: Empty packet for air-purifier.mode, skipping refresh
javascript.0 | 2021-11-08 10:22:04.028 | warn | script.js.Yvonne.Xiaomi_Geräte.Xiaomi: Empty packet for air-purifier.fan-level, skipping refresh
javascript.0 | 2021-11-08 10:22:04.027 | warn | script.js.Yvonne.Xiaomi_Geräte.Xiaomi: Empty packet for air-purifier.on, skipping refresh
javascript.0 | 2021-11-08 10:22:04.026 | warn | script.js.Yvonne.Xiaomi_Geräte.Xiaomi: Empty packet for air-purifier.fault, skipping refresh

**Comment by Pittini** [comment]
> Hilfe, seitdem wird jedoch mein Log geflutet. Ich habe im 5 bis 10 Minuten Rythmus folgende Einträge:

Is nur ne Warnmeldung, hab ich auch 1-4 mal am Tag, sagt nur das Xiomi zwar ein Packet mit Daten angelifert hat, da aber nix drin ist. Kommt entweder wenn die Server bei denen hohe Last haben, oder Du ne lahme Inet Leitung mit PacketLosts. 5 Minuten Takt über längere Zeit deutet aufn Prob bei Dir hin (muß aber nicht sein).

**Comment by stony2k** [comment]
Ich hatte das gleiche Problem, dass das Script plötzlich nicht mehr lief. Auch hier war die Lösung: Aus der Xiaomi App am Handy ausloggen und wieder einloggen.

**Comment by Siggi0904** [comment]
Ja, ich hatte mich gestern auch damit rumgeärgert, dass ich die Daten nicht lesen konnte.
Vielleicht kann man ins Readme folgenden Hinweis übernehmen:

**Wichtiger Hinweis für alle Nutzer:**
Eine doppelte Anmeldung ist schlecht möglich. Also Handy-App und der Zugriff über IOBroker stehen im Konflikt.
Bei der Einrichtung in IOBroker bitte erst am Handy abmelden.
Nach erfolgreicher Einrichtung in IOBroker kann auch am Handy wieder angemeldet werden.

**Comment by Pittini** [comment]
So, nun hatte ich (endlich) auch mal diesen Fehler. Komische Sache, immer noch schwer nachzuvollziehen. Meine Lösung war, kurzeitig den Login auszukommentieren (aktuell Zeile 835), das Skript neu zu starten und schon lief es wieder. DAnn wieder den Login aktiviert und es blieb ok. Vielleicht hilfts ja wem.

**Comment by stony2k** [comment]
Ach sehr gut. Kannst du das (in evtl. meinen Pull Request) evtl. in die Readme übernehmen? :)

**Comment by vsa-d** [comment]
Hallo, leider funktioniert das tolle Script von Dir seit meinem letzten Update von iobroker nicht mehr...
Klar, ich habe dien rasbi neu gestartet, das Skript nochmals heruntergeladen, auch über npm, mich vom Handy ausgeloggt.... dennoch erhalte ich diese Fehlermeldung:

Was könnt ich hier machen? Vg 

`<html><body>


javascript.0 | 2022-01-01 18:09:36.442 | error | at Init (script.js.common.AllMyMi:830:21)
-- | -- | -- | --
javascript.0 | 2022-01-01 18:09:36.442 | error | at MiCloudProtocol.getDevices  (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/protocol-micloud.js:121:18)
javascript.0 | 2022-01-01 18:09:36.441 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
javascript.0 | 2022-01-01 18:09:36.441 | error | at MiCloudProtocol.request  (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/protocol-micloud.js:107:13)
javascript.0 | 2022-01-01 18:09:36.440 | error | script.js.common.AllMyMi: Error: Request error with status Unauthorized
javascript.0 | 2022-01-01 18:09:36.135 | info | script.js.common.AllMyMi: Retrieving your in de registered MiHome Devices
javascript.0 | 2022-01-01 18:09:35.317 | error | at Script.runInContext (vm.js:130:18)
javascript.0 | 2022-01-01 18:09:35.316 | error | at script.js.common.zhimi.airpurifier.mb3:130:3
javascript.0 | 2022-01-01 18:09:35.316 | error | at script.js.common.zhimi.airpurifier.mb3:3:1
javascript.0 | 2022-01-01 18:09:35.315 | error | script.js.common.zhimi.airpurifier.mb3: ReferenceError: module is not defined
javascript.0 | 2022-01-01 18:09:35.314 | info | script.js.common.zhimi.airpurifier.mb3: registered 0 subscriptions and 0 schedules
javascript.0 | 2022-01-01 18:09:35.313 | error | at Script.runInContext (vm.js:130:18)
javascript.0 | 2022-01-01 18:09:35.313 | error | at script.js.common.zhimi.airpurifier.mb3:130:3
javascript.0 | 2022-01-01 18:09:35.312 | error | at script.js.common.zhimi.airpurifier.mb3:1:16
javascript.0 | 2022-01-01 18:09:35.312 | error | at require (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:412:32)
javascript.0 | 2022-01-01 18:09:35.311 | error | at require (internal/modules/cjs/helpers.js:74:18)
javascript.0 | 2022-01-01 18:09:35.311 | error | at Module.require (internal/modules/cjs/loader.js:887:19)
javascript.0 | 2022-01-01 18:09:35.310 | error | script.js.common.zhimi.airpurifier.mb3: Error: Cannot find module '../device-miio'
javascript.0 | 2022-01-01 18:09:35.301 | info | Start javascript script.js.common.zhimi.airpurifier.mb3
javascript.0 | 2022-01-01 18:09:34.965 | info | script.js.common.AllMyMi: registered 0 subscriptions and 0 schedules
javascript.0 | 2022-01-01 18:09:34.902 | info | script.js.common.AllMyMi: Starting AllMyMi V.0.2.28
javascript.0 | 2022-01-01 18:09:34.732 | info | Start javascript script.js.common.AllMyMi


</body>
</html>`

**Comment by Pittini** [comment]
> das Skript nochmals heruntergeladen, auch über npm,

Dann haste das hoffentlich im richtigen Verzeichnis gemacht. Normalerweise wird die node-mihome einfach im JS Adapter eingetragen. Die Fehlermeldung sagt jetzt nix besonderes, geht halt nich. Sollte das gestern gewesen sein, da waren wohl die Xiaomi Server down, bei einigen zickts auch heut noch rum laut Facebook. Im zweifelsfall, komplett neu, genau nach Anleitung nochmal installieren.

**Comment by stony2k** [comment]
@vsa-d Das scheint hier ein anderes Problem zu sein, kannst du aus Gründen der Übersicht bitte eine neue Issue erstellen? Ich habe auch schon eine grobe Tendenz / Idee :)

**Comment by Siggi0904** [comment]
Xiaomi hat wohl das Anmeldeverfahren geändert.
Ich hatte das schon im Adapter zum Staubsauger geschrieben.
Es wurde wohl innerhalb der EU auf RC4 umgestellt und nicht mehr plain Text.

Aber ich kann das nicht bestätigen.

**Comment by stony2k** [comment]
Interessant, hatte mich schon gewundert, dass mein Luftreiniger nicht mehr per Script steuerbar war. Habe gerade das Script mal neugestartet und bekam folgende Meldung (auch nachdem ich mich in der App ausgeloggt hatte):

>script.js.Steuerung.Mi-Home_Geraete: Error: Request error with status Unauthorized
>script.js.Steuerung.Mi-Home_Geraete: Retrieving your in de registered MiHome Devices
>script.js.Steuerung.Mi-Home_Geraete: You are already logged in, login canceled

**Comment by Pittini** [comment]
Please use this Issue: https://github.com/Pittini/iobroker-nodemihome/issues/56

**Comment by Bender275** [comment]
Hallo, bei mir tritt seit ein paar Tagen wieder das Problem mit 

You are already logged in, login canceled
Retrieving your in de registered MiHome Devices
Pls login before make any request

auf.

Ich hatte es auch gelesen, dass man sich überall abmelden muss. Brav gemacht, auch aus der Zapp-App für die Smartwatch - geht trotzdem nicht.
Ich war auch über Stunden abgemeldet, einfach um sicherzugehen, dass ich auch wirklich auf allen Servern bei Xiaomi raus bin - geht immernoch nicht.

Daraufhin habe ich einen neuen User angelegt und mit ihm das Zuhause geteilt, um auch sicherzugehen, dass sich die Anmeldungen nicht in die Quere kommen.
Hilft auch nix, auch hier kommt der Fehler immer weiter.

Noch jemand ne Idee?

Grüße

**Comment by Pittini** [comment]
Ja, es scheint dass da etwas an der Login Prozedur geändert wurde. Das ist sehr schade, denn der Entwickler der node-mihome reagiert schon seit Jahren nicht mehr, somit ist das Skript leider tot.
