### ISSUE TITLE
Error: Model dmaker.fan.p15 is not supported

### ISSUE THREAD

**Issue by Siggi0904** [Pittini/iobroker-nodemihome#49]
Hallo Pittini,

ich bekomme nach der Einrichtung des Scripts und dem Start folgende Fehlermeldungen:
`avascript.0 | 2021-11-06 15:26:27.060 | error | at main (script.js.Skripte.Wohnung.Xiaomi_Geräte:770:5)
javascript.0 | 2021-11-06 15:26:27.060 | error | at processTimers (internal/timers.js:500:7)
javascript.0 | 2021-11-06 15:26:27.060 | error | at listOnTimeout (internal/timers.js:526:9)
javascript.0 | 2021-11-06 15:26:27.060 | error | at runNextTicks (internal/process/task_queues.js:60:5)
javascript.0 | 2021-11-06 15:26:27.059 | error | at CreateDevices (script.js.Skripte.Wohnung.Xiaomi_Geräte:838:36)
javascript.0 | 2021-11-06 15:26:27.054 | error | at Object.createDevice [as device]  (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/device.js:8:11)
javascript.0 | 2021-11-06 15:26:27.054 | error | script.js.Skripte.Wohnung.Xiaomi_Geräte: Error: Model dmaker.fan.p15 is not supported
`
Die Geräte werden auch alle gefunden, er findet auch den Staubsauger Roborock S5.
Aber die von dir unterstützen Luftreiniger und Ventilator sind da.

Leider sind alle Datenpukte mit dem Eintrag (null)
Was kann ich machen, dass das Skript bei mir läuft?

Ich habe folgende Geräte:
1. Luftreiniger Air purifier 3H
2. Ventilator Xiaomi Mi Smart Standing Fan Pro
3. Staubsauger Roborock S5

Danke.

**Comment by Pittini** [comment]
Hast Du die Definitionsdateien einkopiert wie in der Anleitung beschrieben?

**Comment by Siggi0904** [comment]
Hallo,
ja nach dem Hinzufügen der Definitionsdatei für den dmaker.fan.p15 läuft das Script.
Muss ich da noch mehr Dateien hinzufügen, weil du Definitionsdateien geschrieben hattest?

Aktuell gib es zwei Fehlermeldungen.
1. Fehler bei der Erreichbarkeit der API
![grafik](https://user-images.githubusercontent.com/4992106/140646071-3774e801-8232-4f6e-8411-9b081ab0d1bb.png)

2. Motorendaten in den Datenpunkten der Opjekte stehen auf (null)
![grafik](https://user-images.githubusercontent.com/4992106/140646125-0571f519-10c2-44a1-be1f-66d97ef6aa9b.png)

Kannst du da was machen?
Danke übrigens für das tolle Script.

**Comment by Pittini** [comment]
> Muss ich da noch mehr Dateien hinzufügen, weil du Definitionsdateien geschrieben hattest?

Naja, Du hast 2 unterstützte Geräte, also brauchste auch 2 Definitionsdateien.

Die obige Fehlermeldung kommt gelegentlich auch mal bei mir, kannste ignorieren, außer die kommt ständig.
Wenn angelegte Dps nicht gefüllt werden deutet das immer auf nicht vorhandene, oder nicht korrekte Definitionsdateien hin. Die Hauptfrage aber wäre, was steht denn in den anderen Datenpunkten? Werden die befüllt oder sind die auch leer?

**Comment by Siggi0904** [comment]
Hi, ja die anderen Datenpunkte der beiden Geräte werden gefüllt.
Da der Luftreiniger funktionierte, dachte ich, ich brauche keine zusätzliche Definitionsdatei.

Nachdem ich nun die vorhandene Datei mit deiner Datei zhimi.airpurifier.mb3.js für den überschrieben habe,
gehen die Motordaten auch beim Luftreiniger.
Beim Ventilator Xiaomi Mi Smart Standing Fan Pro konnte ich die Motorendaten noch nicht anzeigen.
Wie kann ich hier unterstützen, dass die Motordaten angezeigt werden?

**Wichtiger Hinweis für alle Nutzer:**
Eine doppelte Anmeldung ist schlecht möglich. Also Handy-App und der Zugriff über IOBroker stehen im Konflikt.
Bei der Einrichtung in IOBroker bitte erst am Handy abmelden.
Nach erfolgreicher Einrichtung in IOBroker kann auch am Handy wieder angemeldet werden.

**Comment by Siggi0904** [comment]
Wenn ich das logging aktiviere, kommt die Meldung, dass ich schon angemeldet sei.
`2021-11-08 16:00:58.137  - info: javascript.0 (2406969) Stop script script.js.Skripte.Wohnung.Xiaomi_Geräte
--
2021-11-08 16:01:03.579  - info: javascript.0 (2406969) Start javascript script.js.Skripte.Wohnung.Xiaomi_Geräte
2021-11-08 16:01:03.896  - info: javascript.0 (2406969) script.js.Skripte.Wohnung.Xiaomi_Geräte: Starting AllMyMi V.0.2.27
2021-11-08 16:01:03.896  - info: javascript.0 (2406969) script.js.Skripte.Wohnung.Xiaomi_Geräte: Reaching init
2021-11-08 16:01:03.926  - info: javascript.0 (2406969) script.js.Skripte.Wohnung.Xiaomi_Geräte: registered 0 subscriptions and 0 schedules
2021-11-08 16:01:04.381  - info: javascript.0 (2406969) script.js.Skripte.Wohnung.Xiaomi_Geräte: You are already logged in, login canceled
2021-11-08 16:01:04.382  - info: javascript.0 (2406969) script.js.Skripte.Wohnung.Xiaomi_Geräte: Retrieving your in de registered MiHome Devices
2021-11-08 16:01:04.386  - error: javascript.0 (2406969) script.js.Skripte.Wohnung.Xiaomi_Geräte: Error: Pls login before make any request
2021-11-08 16:01:04.387  - error:  javascript.0 (2406969)     at MiCloudProtocol.request  (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/protocol-micloud.js:67:13)
2021-11-08 16:01:04.387  - error:  javascript.0 (2406969)     at MiCloudProtocol.getDevices  (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/protocol-micloud.js:121:29)
2021-11-08 16:01:04.388  - error: javascript.0 (2406969)     at Init (script.js.Skripte.Wohnung.Xiaomi_Geräte:806:50)
2021-11-08 16:01:04.388  - error: javascript.0 (2406969)     at processTicksAndRejections (internal/process/task_queues.js:95:5)`

**Comment by Pittini** [comment]
> Beim Ventilator Xiaomi Mi Smart Standing Fan Pro konnte ich die Motorendaten noch nicht anzeigen.
> Wie kann ich hier unterstützen, dass die Motordaten angezeigt werden?

Gar nicht. Es wird angezeigt was Xiaomi in der Api zur Verfügung stellt, beim Fan isses das hier: https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:fan:0000A005:dmaker-p15:1

Der einzige Dp bei motor-controller/motor-control is write only, sollte sich setzen lassen, wird aber nicht aktualisiert.

**Comment by Siggi0904** [comment]
Okay und danke für die Info und die json Datei.
Das der Datenpunkt nur beschrieben wird und nicht lesbar ist, ist ja merkwürdig.

Dann könnte man "urn:miot-spec-v2:property:fault:00000009:dmaker-p15:1" als Gerätefehler noch übernehmen.
