### ISSUE TITLE
Add support for sensors/switches

### ISSUE THREAD

**Issue by bortpasc** [Pittini/iobroker-nodemihome#5]
Integration Xiaomi hub EU version isn't possible via mihome adapter. This way via cloud is much better. It would be nice if the sensors and the switches would work too. If possible also the hub. THX

**Comment by Pittini** [comment]
Its not planned atm to integrate zigbee devices, there are enough possibilities to integrate them in iobroker via another coordinator as ConBee2 oder cc26x2r1 Board.

**Comment by bortpasc** [comment]
Yes i know, but there are no solutions for integration of the EU hub with alarm functions. I think the way via cloud is the easiest way, but there are no others solutions in the WEB...
