### ISSUE TITLE
yeelink.light.bslamp2

### ISSUE THREAD

**Issue by tobasium** [Pittini/iobroker-nodemihome#52]
Hi, 

nach dem ich jetzt dank Firmware update meine Lampe nicht mehr ansteuern (LAN Control deaktiviert) kann wollte ich hier nochmal anfragen ob wir zusammen das config file erstellen und testen.

Info Daten werden angezeigt.

**Comment by Pittini** [comment]
Ich hab da mal was vorbereitet.... :) - https://github.com/Pittini/iobroker-nodemihome/blob/main/HowToAddNewDevices.md

**Comment by tobasium** [comment]
Super Danke,

Also ich bin dann soweit fertig.
Ich hab mich an den anderen Yeelight lampen orientiert.

Angezeigt bekomme ich die Werte.
Ich habe jetzt nur das Problem anschalten geht, ausschalten nicht.
Schalten kann ich nur bright

Hast du hier auf die schnelle ein Tip?

[Propertys](https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:light:0000A001:yeelink-bslamp2:1)


[yeelink.light.bslamp2.js.zip](https://github.com/Pittini/iobroker-nodemihome/files/7660461/yeelink.light.bslamp2.js.zip)

**Comment by tobasium** [comment]
Ok ich bin dann nochmal etwas weiter.

Habe das script angepasst.
Power lässt sich nun schalten.
RGB noch nicht

**Comment by Pittini** [comment]
> RGB noch nicht

![2021-12-06 14_16_17-Pittini_iobroker-nodemihome_ Steuerung von bisher nicht unterstützten Xiaomi Ger](https://user-images.githubusercontent.com/51408942/144852669-16ab29c2-cf8b-4cc4-aa15-ce786952558d.png)

Hab leider nie rausgefunden wie node-mihome die Farbe gern hätte. Und vom Dev kriegt man ja keine Reaktion auf Fragen, da wirste also erstmal mit leben müssen.

Ansonsten, prima Vorbereitung (bitte in Zukunft aber aktuelle Version dafür nehmen), werd ich erstmal in den Dev Zweig übernehmen, dann kannst nochma testen.

**Comment by tobasium** [comment]
Super, 

Ja irgendwie hab ich das Update nicht gesehen. habe nochmal mein script entfernt da login Daten vergessen zu entfernen. SHAME on me

**Comment by tobasium** [comment]
So anbei mal die richtige Variante neuste Version
[script-1.zip](https://github.com/Pittini/iobroker-nodemihome/files/7661034/script-1.zip)

**Comment by Pittini** [comment]
So, is in der neuen Dev drin, bitte nochmal drüberguggen und dann freigeben

**Comment by tobasium** [comment]
Jop sieht gut aus hab es getestet es geht.

**Comment by tobasium** [comment]
@Pittini kannst du die bslamp noch in den main übernehmen. Danke
