### ISSUE TITLE
Error: Request error with status Unauthorized

### ISSUE THREAD

**Issue by Pittini** [Pittini/iobroker-nodemihome#56]
Since some hours there appears the error: "Error: Request error with status Unauthorized" and the script doesnt work anymore

It looks like there are breaking changes in the Xiaomi login procedure. To solve this problem, node-mihome has to be updated. I dont know if or when the node-mihome developer will do this. So my script is completely disfunctional atm, sorry by that.

**Comment by dontobi** [comment]
Ich habe diesen Fehler heute morgen auch erhalten. Habe bereits ein paar Tests durchgeführt, aber nichts hat geholfen.

Solltest du etwas testen wollen, stehe ich gerne zur Verfügung. Solltest du mich anschreiben wollen, ich bin auch über den ioBroker Discord Server erreichbar. Mein Handle dort ist "dontobi" oder du schreibst mich direkt an (Handle: dontobi#3869).

**Comment by Crash343** [comment]
> Ich habe diesen Fehler heute morgen auch erhalten. Habe bereits ein paar Tests durchgeführt, aber nichts hat geholfen.
> 
> Solltest du etwas testen wollen, stehe ich gerne zur Verfügung. Solltest du mich anschreiben wollen, ich bin auch über den ioBroker Discord Server erreichbar. Mein Handle dort ist "dontobi" oder du schreibst mich direkt an (Handle: dontobi#3869).

Problem ist bei mir auch vorhanden. Wäre auch für Tests bereit. Gerne melden...

**Comment by klenzel** [comment]
Interessanterweise läuft nur "de" in diesen Fehler. CN meldet bei mir zwar richtigerweise, dass keine Geräte gefunden wurden, aber kein Login-Fehler. Vielleicht ist das bei der Fehlersuche hilfreich.

**Comment by Pittini** [comment]
> Interessanterweise läuft nur "de" in diesen Fehler. CN meldet bei mir zwar richtigerweise, dass keine Geräte gefunden wurden, aber kein Login-Fehler. Vielleicht ist das bei der Fehlersuche hilfreich.

Ja, ist bekannt. Scheint nur die EU Server zu betreffen.

**Comment by Pittini** [comment]
Seems to be fixed by Xiaomi. Now again working as usual.
