### ISSUE TITLE
Error mit Xiaomi Smart Fan 3

### ISSUE THREAD

**Issue by iobroker-nutzer** [Pittini/iobroker-nodemihome#62]
Hallo, 
Ich habe laut Anleitung das Skript gestartet und die Datei zhimi.fan.za5.js in das Verzeichnis kopiert.
(Im Skript selber steht der Ventilator drinne, es wurde beim ersten Start des Skriptes aber keine entsprechende Datei angelegt.)
Nach dem Neustart des Skipts erscheinen folgende Fehlermeldungen:

```
12:41:20.822 | info | javascript.0 (532927) Start javascript script.js.Aktionen.AllMyMi

12:41:20.956 | error | javascript.0 (532927) script.js.Aktionen.AllMyMi: /opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/devices/zhimi.fan.za5.js:8
12:41:20.963 | error | javascript.0 (532927) at script.js.Aktionen.AllMyMi:3:16
12:41:20.963 | error | javascript.0 (532927) at script.js.Aktionen.AllMyMi:1190:3
12:41:20.964 | info | javascript.0 (532927) script.js.Aktionen.AllMyMi: Starting AllMyMi V.0.2.29
12:41:20.966 | info | javascript.0 (532927) script.js.Aktionen.AllMyMi: registered 0 subscriptions and 0 schedules
12:41:20.968 | error | javascript.0 (532927) script.js.Aktionen.AllMyMi: TypeError: Cannot read property 'miioProtocol' of undefined
12:41:20.968 | error | javascript.0 (532927) at Init (script.js.Aktionen.AllMyMi:865:12)
12:41:20.969 | error | javascript.0 (532927) at script.js.Aktionen.AllMyMi:37:1
12:41:20.969 | error | javascript.0 (532927) at script.js.Aktionen.AllMyMi:1190:3

```

Hab ich was falsch gemacht (da bin ich mir ziemlich sicher), oder können bei dem selben Ventilator unterschiedliche Protokolle verwendet werden (mein Laienhaftes Take-away der Fehlermeldung)?

Vielen Dank

**Comment by Pittini** [comment]
Hast Du auch den JS Controller neugestartet oder nur das Skript, nach dem einkopieren der Datei?

**Comment by iobroker-nutzer** [comment]
Den ganzen iobroker und auch den Javascript Adapter.

Edit: Kann es evtl. an falschen Zugriffsrechten liegen?

**Comment by iobroker-nutzer** [comment]
Fehler gefunden. Er befindet sich 50 cm vor dem Bildschirm. 
Ich habe beim download des Device-Scripts nicht aufgepasst und dadurch war ein komplett anderer Inhalt in dem Skript.
Ist mein erster Tag bei Github...
Vielen Dank für die Arbeit an dem Skript!
