### ISSUE TITLE
Neustart Javascript-Adapter mit node-mihome build

### ISSUE THREAD

**Issue by Siggi0904** [Pittini/iobroker-nodemihome#68]
Wenn ich den iobroker neu starte und der Javascript-Adapter per npm das zusätzliche NPM-Module "node-mihome" baut,
läuft danach folgender Fehler auf.

Is das bekannt? Muss da die node-mihome Erweiterung aktualisiert werden?

javascript.0 | 2023-09-18 22:16:35.179 | info | 2 moderate severity vulnerabilities  Some issues need review, and may require choosing a different dependency.  Run `npm audit` for details.
-- | -- | -- | --
javascript.0 | 2023-09-18 22:16:35.145 | info | run `npm fund` for details
javascript.0 | 2023-09-18 22:16:35.141 | info | 8 packages are looking for funding
javascript.0 | 2023-09-18 22:16:35.136 | info |  
javascript.0 | 2023-09-18 22:16:35.129 | info | added 126 packages, and audited 128 packages in 1m
javascript.0 | 2023-09-18 22:16:32.728 | error | WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
javascript.0 | 2023-09-18 22:16:32.726 | error |  
javascript.0 | 2023-09-18 22:16:32.723 | error | npm
javascript.0 | 2023-09-18 22:16:32.635 | error | WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.   Older versions may use Math.random() in certain circumstances, which is  known to be problematic.  See https://v8.dev/blog/math-random for  details.
javascript.0 | 2023-09-18 22:16:32.632 | error |  
javascript.0 | 2023-09-18 22:16:32.629 | error | npm
javascript.0 | 2023-09-18 22:16:32.535 | error | WARN deprecated node-inspect@2.0.0: This module is part of Node.js  core and does not need to be installed separately. It is now  unmaintained.
javascript.0 | 2023-09-18 22:16:32.532 | error |  
javascript.0 | 2023-09-18 22:16:32.529 | error | npm
javascript.0 | 2023-09-18 22:16:32.259 | error | WARN deprecated har-validator@5.1.5: this library is no longer supported
javascript.0 | 2023-09-18 22:16:32.257 | error |  
javascript.0 | 2023-09-18 22:16:32.253 | error | npm
javascript.0 | 2023-09-18 22:15:34.204 | info | npm install node-mihome --omit=dev (System call)
javascript.0 | 2023-09-18 22:15:34.106 | info | starting. Version 7.1.4 in /opt/iobroker/node_modules/iobroker.javascript, node: v18.17.1, js-controller: 5.0.12

Danke im Voraus.

**Comment by Pittini** [comment]
Scheint an node-mihome zu liegen und da kann ich leider nix machen da der Entwickler seit Ewigkeiten auf nix reagiert.

**Comment by Siggi0904** [comment]
Hallo Pittini,
sowas dachte ich mir schon.

Kannst du den node-mihome forken und das Problem beheben?

Danke.

**Comment by Pittini** [comment]
> Hallo Pittini, sowas dachte ich mir schon.
> 
> Kannst du den node-mihome forken und das Problem beheben?
> 
> Danke.

Wenn ich das könnte, hätte ichs schon lang gemacht (forken kann ich natürlich, das wars dann aber auch). Unabhängig davon hab ich gestern hier mein System neu aufgesetzt und keinerlei Probleme mit der node-mihome. Das nur zur Info, evtl. passt ja auch iwas bei Dir nicht.

**Comment by Siggi0904** [comment]
Ich bekomme die Fehlermeldung nur, wenn ich das System neu starte.
Beim Neustart vom iobroker kommt das nicht,

Kann aber auch daran liegen, dass bei einem Neustart/Update einige Definitionsdateien immer neu in den Ordner inzugefügt werden müssen.

**Comment by Pittini** [comment]
Da wir hier nicht zu nem Ergebnis kommen werden, mach ich mal zu.
