### ISSUE TITLE
Prerequisites for Pi 4 and this script?

### ISSUE THREAD

**Issue by AhzurdanGit** [Pittini/iobroker-nodemihome#7]
I try to run that but get following error message on starting the script:
Anything I am missing potentially?

best regards,
Ahzurdan

javascript.0 | 2021-01-28 15:17:41.981 | info | (2380) script.js.skripte.Allgemein.Purify: registered 0 subscriptions and 0 schedules
-- | -- | -- | --
javascript.0 | 2021-01-28 15:17:41.975 | info | (2380) script.js.skripte.Allgemein.Purify: Reaching init
javascript.0 | 2021-01-28 15:17:41.974 | info | (2380) script.js.skripte.Allgemein.Purify: Starting AllMyMi V.0.2.7
javascript.0 | 2021-01-28 15:17:41.974 | error | (2380) at Script.runInContext (vm.js:133:20)
javascript.0 | 2021-01-28 15:17:41.974 | error | (2380) at script.js.skripte.Allgemein.Purify:3:16
javascript.0 | 2021-01-28 15:17:41.974 | error | (2380) at require (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:389:36)
javascript.0 | 2021-01-28 15:17:41.973 | error | (2380) at require (internal/modules/cjs/helpers.js:25:18)
javascript.0 | 2021-01-28 15:17:41.973 | error | (2380) at Module.require (internal/modules/cjs/loader.js:692:17)
javascript.0 | 2021-01-28 15:17:41.973 | error | (2380) at Function.Module._load (internal/modules/cjs/loader.js:585:3)
javascript.0 | 2021-01-28 15:17:41.973 | error | (2380) at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
javascript.0 | 2021-01-28 15:17:41.973 | error | (2380) at Module.load (internal/modules/cjs/loader.js:653:32)
javascript.0 | 2021-01-28 15:17:41.973 | error | (2380) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
javascript.0 | 2021-01-28 15:17:41.972 | error | (2380) at Module._compile (internal/modules/cjs/loader.js:778:30)
javascript.0 | 2021-01-28 15:17:41.972 | error | (2380) at Object.<anonymous> (/opt/iobroker/node_modules/node-mihome/lib/index.js:5:16)
javascript.0 | 2021-01-28 15:17:41.972 | error | (2380) at require (internal/modules/cjs/helpers.js:25:18)
javascript.0 | 2021-01-28 15:17:41.972 | error | (2380) at Module.require (internal/modules/cjs/loader.js:692:17)
javascript.0 | 2021-01-28 15:17:41.972 | error | (2380) at Function.Module._load (internal/modules/cjs/loader.js:585:3)
javascript.0 | 2021-01-28 15:17:41.972 | error | (2380) at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
javascript.0 | 2021-01-28 15:17:41.972 | error | (2380) at Module.load (internal/modules/cjs/loader.js:653:32)
javascript.0 | 2021-01-28 15:17:41.971 | error | (2380) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
javascript.0 | 2021-01-28 15:17:41.971 | error | (2380) at Module._compile (internal/modules/cjs/loader.js:778:30)
javascript.0 | 2021-01-28 15:17:41.971 | error | (2380) at Object.<anonymous> (/opt/iobroker/node_modules/node-mihome/lib/device.js:1:16)
javascript.0 | 2021-01-28 15:17:41.971 | error | (2380) at require (internal/modules/cjs/helpers.js:25:18)
javascript.0 | 2021-01-28 15:17:41.971 | error | (2380) at Module.require (internal/modules/cjs/loader.js:692:17)
javascript.0 | 2021-01-28 15:17:41.971 | error | (2380) at Function.Module._load (internal/modules/cjs/loader.js:585:3)
javascript.0 | 2021-01-28 15:17:41.970 | error | (2380) at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
javascript.0 | 2021-01-28 15:17:41.970 | error | (2380) at Module.load (internal/modules/cjs/loader.js:653:32)
javascript.0 | 2021-01-28 15:17:41.970 | error | (2380) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
javascript.0 | 2021-01-28 15:17:41.970 | error | (2380) at Module._compile (internal/modules/cjs/loader.js:778:30)
javascript.0 | 2021-01-28 15:17:41.970 | error | (2380) at Object.<anonymous> (/opt/iobroker/node_modules/node-mihome/lib/models.js:6:54)
javascript.0 | 2021-01-28 15:17:41.970 | error | (2380) at Array.forEach (<anonymous>:null:null)
javascript.0 | 2021-01-28 15:17:41.969 | error | (2380) at glob.sync.forEach.modelPath (/opt/iobroker/node_modules/node-mihome/lib/models.js:9:23)
javascript.0 | 2021-01-28 15:17:41.969 | error | (2380) at require (internal/modules/cjs/helpers.js:25:18)
javascript.0 | 2021-01-28 15:17:41.969 | error | (2380) at Module.require (internal/modules/cjs/loader.js:692:17)
javascript.0 | 2021-01-28 15:17:41.969 | error | (2380) at Function.Module._load (internal/modules/cjs/loader.js:585:3)
javascript.0 | 2021-01-28 15:17:41.969 | error | (2380) at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
javascript.0 | 2021-01-28 15:17:41.968 | error | (2380) at Module.load (internal/modules/cjs/loader.js:653:32)
javascript.0 | 2021-01-28 15:17:41.968 | error | (2380) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
javascript.0 | 2021-01-28 15:17:41.968 | error | (2380) script.js.skripte.Allgemein.Purify: /opt/iobroker/node_modules/node-mihome/lib/devices/imibar.cooker.mbihr3.js:26

**Comment by Pittini** [comment]
(2380) at script.js.skripte.Allgemein.Purify:3:16 is das Problem, was danach kommt sind folgefehler würd ich sagen. Zeile 3 is das `const mihome = require('node-mihome');`

Also passt iwas mit node-mihome nicht. Auch seltsam ist der Pfad den ich im letzten Logeintrag seh, bei mir sieht der so aus, 
`/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/devices/`
aber evtl. is das wegen pi. Jedenfalls, das Problem is nicht das Skript, sondern die Einbindung von node-mihome

**Comment by Pittini** [comment]
Inactivity close
