### ISSUE TITLE
Syntax Error const

### ISSUE THREAD

**Issue by jonaschuba** [Pittini/iobroker-nodemihome#8]
Hello, I don't know why I get this error by uploading the script.

SyntaxError: JSON Parse error: Unexpected identifier "const"

Thanks

**Comment by jonaschuba** [comment]
ScripEngine version 4.8.4

**Comment by Pittini** [comment]
I dont know what you are doing and you are providing zero info for me, no log, no exactly describtion when the error occurs, nothing, so i close here
